#!/usr/bin/env node
const input = JSON.parse(require('fs').readFileSync(0, 'utf-8'));

console.log(JSON.stringify({
  cancel: false,
  contextModification: "TaskStart hook executed successfully",
  errorMessage: ""
}));
