export const CLINE_RPC_PORT = 25463;
export const CLINE_DEFAULT_RPC_PORT = 4317;
export const RPC_ADDRESS_BASE = "127.0.0.1";
export const CLINE_DEFAULT_RPC_ADDRESS = `${RPC_ADDRESS_BASE}:${CLINE_DEFAULT_RPC_PORT}`;
