export const BEDROCK_CODER_HUB_PORT = 25463; // BEDROCK_CODER
export const BEDROCK_CODER_HUB_DEV_PORT = 25466; // USED IN DEV ENV ONLY, to avoid conflicts with production BEDROCK_CODER HUB
export const BEDROCK_CODER_DEFAULT_RPC_PORT = 4317;
export const RPC_ADDRESS_BASE = "127.0.0.1";
export const BEDROCK_CODER_DEFAULT_RPC_ADDRESS = `${RPC_ADDRESS_BASE}:${BEDROCK_CODER_DEFAULT_RPC_PORT}`;
