// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by proto/build-proto.js

import { createChannel, createClientFactory, Client } from "nice-grpc"
import { Channel } from "@grpc/grpc-js"

const channel = createChannel("localhost:50051") // Replace with your server address

export function createGrpcClient<T extends {}>(definition: any): Client<T> {
	return createClientFactory().create(definition, channel)
}
