#!/usr/bin/env node
/**
 * Fault-injection mock for an OpenAI-compatible provider.
 *
 * Behaviour is selected by the `model` field of the request, so a QA run can
 * switch faults from the Cline settings UI without touching this process.
 *
 * Endpoints:
 *   GET  /v1/models                 fault model catalogue
 *   POST /v1/chat/completions       fault behaviour, keyed by `model`
 *   GET  /__qa/requests             observed requests (JSON)
 *   GET  /__qa/health               liveness
 *   POST /__qa/reset                clear the request log
 *
 * Authorization values are never stored: only a short digest, the length, and
 * whether the value carried surrounding whitespace (needed to check that Cline
 * trims keys pasted with a trailing newline).
 */
import { createHash } from "node:crypto"
import { appendFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { createServer } from "node:http"
import { dirname } from "node:path"

const PORT = Number(process.env.QA_PROXY_PORT || 8788)
const HOST = process.env.QA_PROXY_HOST || "127.0.0.1"
const LOG_PATH = process.env.QA_PROXY_LOG || "/tmp/qa-proxy/requests.jsonl"

mkdirSync(dirname(LOG_PATH), { recursive: true })

const FAULT_MODELS = [
	"fault/ok",
	"fault/ok-no-cache",
	"fault/big-usage",
	"fault/zero-usage",
	"fault/no-usage",
	"fault/401",
	"fault/402",
	"fault/429",
	"fault/context-overflow",
	"fault/500",
	"fault/hang",
	"fault/truncated-stream",
	"fault/slow-stream",
	// Diagnostic: cache writes reported only inside prompt_tokens_details, which
	// is the shape some OpenAI-compatible gateways use.
	"fault/nested-cache-write",
]

const OK_TEXT =
	"Cost accounting check: this reply is generated by the QA fault proxy so the " +
	"usage numbers attached to it are fixed and known in advance. Nothing here was " +
	"produced by a language model."

const USAGE = {
	// Both shapes seen in the wild are reported together: OpenRouter passes
	// Anthropic cache writes through at the top level, other gateways nest them
	// under prompt_tokens_details.
	"fault/ok": {
		prompt_tokens: 4213,
		completion_tokens: 118,
		total_tokens: 4331,
		prompt_tokens_details: { cached_tokens: 3072, cache_write_tokens: 1024 },
		cache_creation_input_tokens: 1024,
	},
	"fault/nested-cache-write": {
		prompt_tokens: 4213,
		completion_tokens: 118,
		total_tokens: 4331,
		prompt_tokens_details: { cached_tokens: 3072, cache_write_tokens: 1024 },
	},
	"fault/ok-no-cache": {
		prompt_tokens: 4213,
		completion_tokens: 118,
		total_tokens: 4331,
	},
	"fault/big-usage": {
		prompt_tokens: 1200000,
		completion_tokens: 90000,
		total_tokens: 1290000,
	},
	"fault/zero-usage": {
		prompt_tokens: 0,
		completion_tokens: 0,
		total_tokens: 0,
		prompt_tokens_details: { cached_tokens: 0, cache_write_tokens: 0 },
	},
}

const TERMINAL_TOOL_PREFERENCE = [
	"submit_and_exit",
	"attempt_completion",
	"complete_task",
	"finish",
]

let requestSeq = 0

function digest(value) {
	return createHash("sha256").update(value).digest("hex").slice(0, 12)
}

function describeAuth(header) {
	if (!header) {
		return { present: false }
	}
	const bearer = header.replace(/^Bearer\s*/i, "")
	return {
		present: true,
		length: bearer.length,
		digest: digest(bearer),
		hasSurroundingWhitespace: bearer !== bearer.trim(),
	}
}

function record(entry) {
	const line = JSON.stringify({ seq: ++requestSeq, at: new Date().toISOString(), ...entry })
	appendFileSync(LOG_PATH, `${line}\n`)
	process.stdout.write(`${line}\n`)
}

function readLog() {
	try {
		return readFileSync(LOG_PATH, "utf8")
			.split("\n")
			.filter((line) => line.trim().length > 0)
			.map((line) => JSON.parse(line))
	} catch {
		return []
	}
}

function json(res, status, body, headers = {}) {
	const payload = JSON.stringify(body)
	res.writeHead(status, {
		"content-type": "application/json",
		"content-length": Buffer.byteLength(payload),
		...headers,
	})
	res.end(payload)
}

function sseHead(res) {
	res.writeHead(200, {
		"content-type": "text/event-stream",
		"cache-control": "no-cache",
		connection: "keep-alive",
	})
}

function chunk(model, delta, finishReason = null, usage) {
	const body = {
		id: "chatcmpl-qa-fault",
		object: "chat.completion.chunk",
		created: Math.floor(Date.now() / 1000),
		model,
		choices: [{ index: 0, delta, logprobs: null, finish_reason: finishReason }],
	}
	if (usage !== undefined) {
		body.usage = usage
	}
	return `data: ${JSON.stringify(body)}\n\n`
}

/** Build plausible arguments for a tool from its JSON schema. */
function argsForSchema(schema) {
	const properties = schema?.properties ?? {}
	const required = Array.isArray(schema?.required) ? schema.required : Object.keys(properties)
	const args = {}
	for (const name of required) {
		const property = properties[name] ?? {}
		const type = Array.isArray(property.type) ? property.type[0] : property.type
		switch (type) {
			case "boolean":
				args[name] = true
				break
			case "number":
			case "integer":
				args[name] = 1
				break
			case "array":
				args[name] = []
				break
			case "object":
				args[name] = {}
				break
			default:
				args[name] =
					"QA fault proxy reply. Fixed usage numbers were attached to this turn."
		}
	}
	return args
}

/**
 * Pick the tool that ends the run. Without it the agent loop appends a
 * completion reminder and issues another request, which would make the
 * per-message token accounting non-deterministic.
 */
function terminalToolCall(body) {
	const tools = Array.isArray(body?.tools) ? body.tools : []
	const byName = new Map()
	for (const tool of tools) {
		const fn = tool?.function ?? tool
		if (fn?.name) {
			byName.set(fn.name, fn)
		}
	}
	for (const name of TERMINAL_TOOL_PREFERENCE) {
		const fn = byName.get(name)
		if (fn) {
			return { name, args: argsForSchema(fn.parameters ?? fn.input_schema) }
		}
	}
	return undefined
}

function streamOk(res, model, body, usage) {
	sseHead(res)
	res.write(chunk(model, { role: "assistant", content: "" }))
	for (const word of OK_TEXT.split(" ")) {
		res.write(chunk(model, { content: `${word} ` }))
	}
	const tool = terminalToolCall(body)
	if (tool) {
		res.write(
			chunk(model, {
				tool_calls: [
					{
						index: 0,
						id: "call_qa_fault_1",
						type: "function",
						function: { name: tool.name, arguments: "" },
					},
				],
			}),
		)
		res.write(
			chunk(model, {
				tool_calls: [
					{ index: 0, function: { arguments: JSON.stringify(tool.args) } },
				],
			}),
		)
	}
	res.write(chunk(model, {}, tool ? "tool_calls" : "stop", usage))
	res.write("data: [DONE]\n\n")
	res.end()
}

function nonStreamOk(res, model, usage) {
	json(res, 200, {
		id: "chatcmpl-qa-fault",
		object: "chat.completion",
		created: Math.floor(Date.now() / 1000),
		model,
		choices: [
			{
				index: 0,
				message: { role: "assistant", content: OK_TEXT },
				finish_reason: "stop",
			},
		],
		...(usage ? { usage } : {}),
	})
}

const HTML_500 = `<!DOCTYPE html>
<html><head><title>500 Internal Server Error</title></head>
<body><h1>Internal Server Error</h1>
<p>The upstream inference host returned an unexpected condition. Request id 9f2c41b0.</p>
<hr><address>qa-fault-proxy/1.0 at 127.0.0.1 Port 8788</address></body></html>`

function handleChatCompletions(req, res, raw) {
	let body = {}
	try {
		body = JSON.parse(raw || "{}")
	} catch {
		body = {}
	}
	const model = typeof body.model === "string" ? body.model : "(missing)"
	const streaming = body.stream !== false
	record({
		kind: "chat.completions",
		model,
		stream: streaming,
		messageCount: Array.isArray(body.messages) ? body.messages.length : 0,
		toolCount: Array.isArray(body.tools) ? body.tools.length : 0,
		auth: describeAuth(req.headers.authorization),
		promptChars: raw.length,
	})

	switch (model) {
		case "fault/401":
			return json(res, 401, {
				error: {
					message:
						"Incorrect API key provided. You can find your API key at https://example.invalid/keys.",
					type: "invalid_request_error",
					param: null,
					code: "invalid_api_key",
				},
			})
		case "fault/402":
			return json(res, 402, {
				error: {
					message:
						"You have insufficient credits to complete this request. Add credits at https://example.invalid/billing to continue.",
					type: "insufficient_quota",
					param: null,
					code: "insufficient_credits",
				},
			})
		case "fault/429":
			return json(
				res,
				429,
				{
					error: {
						message:
							"Rate limit reached for fault/429 in organization org-qa on requests per min. Limit: 3/min. Please try again in 20s.",
						type: "requests",
						param: null,
						code: "rate_limit_exceeded",
					},
				},
				{ "retry-after": "20" },
			)
		case "fault/context-overflow":
			return json(res, 400, {
				error: {
					message:
						"This model's maximum context length is 8192 tokens. However, your messages resulted in 41237 tokens. Please reduce the length of the messages.",
					type: "invalid_request_error",
					param: "messages",
					code: "context_length_exceeded",
				},
			})
		case "fault/500": {
			res.writeHead(500, {
				"content-type": "text/html; charset=utf-8",
				"content-length": Buffer.byteLength(HTML_500),
			})
			return res.end(HTML_500)
		}
		case "fault/hang": {
			// Headers are never sent and the socket stays open.
			req.on("close", () => record({ kind: "hang.closed", model }))
			return
		}
		case "fault/truncated-stream": {
			sseHead(res)
			res.write(chunk(model, { role: "assistant", content: "" }))
			res.write(chunk(model, { content: "Partial answer that stops mid-" }))
			res.write('data: {"id":"chatcmpl-qa-fault","object":"chat.completion.chu')
			return res.socket?.destroy()
		}
		case "fault/slow-stream": {
			sseHead(res)
			res.write(chunk(model, { role: "assistant", content: "" }))
			let index = 0
			const words = "one token every three seconds keeps this stream open for a long time".split(" ")
			const timer = setInterval(() => {
				if (res.writableEnded) {
					clearInterval(timer)
					return
				}
				if (index >= words.length) {
					clearInterval(timer)
					res.write(chunk(model, {}, "stop", USAGE["fault/ok-no-cache"]))
					res.write("data: [DONE]\n\n")
					res.end()
					return
				}
				res.write(chunk(model, { content: `${words[index++]} ` }))
			}, 3000)
			req.on("close", () => {
				clearInterval(timer)
				record({ kind: "slow.closed", model, tokensSent: index })
			})
			return
		}
		case "fault/no-usage":
			return streaming
				? streamOk(res, model, body, undefined)
				: nonStreamOk(res, model, undefined)
		default: {
			const usage = USAGE[model] ?? USAGE["fault/ok"]
			return streaming
				? streamOk(res, model, body, usage)
				: nonStreamOk(res, model, usage)
		}
	}
}

const server = createServer((req, res) => {
	const url = new URL(req.url ?? "/", `http://${HOST}:${PORT}`)

	if (req.method === "OPTIONS") {
		res.writeHead(204, { "access-control-allow-origin": "*", "access-control-allow-headers": "*" })
		return res.end()
	}

	if (url.pathname === "/__qa/health") {
		return json(res, 200, { ok: true, pid: process.pid, models: FAULT_MODELS })
	}
	if (url.pathname === "/__qa/requests") {
		return json(res, 200, { requests: readLog() })
	}
	if (url.pathname === "/__qa/reset" && req.method === "POST") {
		writeFileSync(LOG_PATH, "")
		requestSeq = 0
		return json(res, 200, { ok: true })
	}
	if (url.pathname === "/v1/models" || url.pathname === "/models") {
		record({ kind: "models.list", auth: describeAuth(req.headers.authorization) })
		return json(res, 200, {
			object: "list",
			data: FAULT_MODELS.map((id) => ({
				id,
				object: "model",
				created: 1700000000,
				owned_by: "qa-fault-proxy",
			})),
		})
	}
	if (url.pathname.endsWith("/chat/completions")) {
		let raw = ""
		req.on("data", (part) => {
			raw += part
		})
		req.on("end", () => handleChatCompletions(req, res, raw))
		return
	}

	record({ kind: "unhandled", method: req.method, path: url.pathname })
	return json(res, 404, { error: { message: `Unhandled path ${url.pathname}`, code: "not_found" } })
})

server.on("clientError", (_error, socket) => socket.destroy())
server.listen(PORT, HOST, () => {
	process.stdout.write(`qa-fault-proxy listening on http://${HOST}:${PORT} (log ${LOG_PATH})\n`)
})
