if(CONFIG_DEVICE_BOARD_EPAPER_154)
    set(board_sources "epaper/board.c" "epaper/audio.c" "epaper/epd.c" "epaper/touch.c")
elseif(CONFIG_DEVICE_BOARD_AMOLED_175C)
    set(board_sources "amoled/board.c")
elseif(CONFIG_DEVICE_BOARD_CARDPUTER_ADV)
    set(board_sources "cardputer/board.c" "cardputer/display.c" "cardputer/keyboard.c" "cardputer/audio.c")
elseif(NOT CMAKE_BUILD_EARLY_EXPANSION)
    message(FATAL_ERROR "Select a supported Cline board profile")
endif()
idf_component_register(SRCS ${board_sources} INCLUDE_DIRS "include" PRIV_INCLUDE_DIRS "epaper" REQUIRES cline_model esp_driver_i2s esp_driver_i2c esp_driver_spi esp_driver_gpio esp_lcd esp_timer)
