// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by proto/build-proto.js

import { createServiceRegistry, ServiceMethodHandler, StreamingMethodHandler } from "../host-grpc-service"
import { registerAllMethods } from "./methods"

// Create window service registry
const windowService = createServiceRegistry("window")

// Export the method handler types and registration function
export type WindowMethodHandler = ServiceMethodHandler
export type WindowStreamingMethodHandler = StreamingMethodHandler
export const registerMethod = windowService.registerMethod

// Export the request handlers
export const handleWindowServiceRequest = windowService.handleRequest
export const handleWindowServiceStreamingRequest = windowService.handleStreamingRequest
export const isStreamingMethod = windowService.isStreamingMethod

// Register all window methods
registerAllMethods()
