// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by proto/build-proto.js

// Import all method implementations
import { registerMethod } from "./index"
import { showMessage } from "./showMessage"
import { showOpenDialogue } from "./showOpenDialogue"
import { showTextDocument } from "./showTextDocument"

// Register all window service methods
export function registerAllMethods(): void {
	// Register each method with the registry
	registerMethod("showMessage", showMessage)
	registerMethod("showOpenDialogue", showOpenDialogue)
	registerMethod("showTextDocument", showTextDocument)
}
