#!/usr/bin/env node
const input = JSON.parse(require('fs').readFileSync(0, 'utf-8'));
const size = input.userPromptSubmit.prompt.length;
console.log(JSON.stringify({
  cancel: false,
  contextModification: "Prompt size: " + size,
  errorMessage: ""
}));
