export const GIT_DISABLED_SUFFIX = "_disabled"

export const GIT_EXCLUDES = [
	".git/", // Ignore the user's .git.
	`.git${GIT_DISABLED_SUFFIX}/`, // Ignore the disabled nested git repos.
	".DS_Store",
	"*.log",
	"node_modules/",
	"__pycache__/",
	"env/",
	"venv/",
	"target/dependency/",
	"build/dependencies/",
	"dist/",
	"out/",
	"bundle/",
	"vendor/",
	"tmp/",
	"temp/",
	"deps/",
	"pkg/",
	"Pods/",
	// Media files.
	"*.jpg",
	"*.jpeg",
	"*.png",
	"*.gif",
	"*.bmp",
	"*.ico",
	// "*.svg",
	"*.mp3",
	"*.mp4",
	"*.wav",
	"*.avi",
	"*.mov",
	"*.wmv",
	"*.webm",
	"*.webp",
	"*.m4a",
	"*.flac",
	// Build and dependency directories.
	"build/",
	"bin/",
	"obj/",
	".gradle/",
	".idea/",
	".vscode/",
	".vs/",
	"coverage/",
	".next/",
	".nuxt/",
	// Cache and temporary files.
	"*.cache",
	"*.tmp",
	"*.temp",
	"*.swp",
	"*.swo",
	"*.pyc",
	"*.pyo",
	".pytest_cache/",
	".eslintcache",
	// Environment and config files.
	".env*",
	"*.local",
	"*.development",
	"*.production",
	// Large data files.
	"*.zip",
	"*.tar",
	"*.gz",
	"*.rar",
	"*.7z",
	"*.iso",
	"*.bin",
	"*.exe",
	"*.dll",
	"*.so",
	"*.dylib",
	// Database files.
	"*.sqlite",
	"*.db",
	"*.sql",
	// Log files.
	"*.logs",
	"*.error",
	"npm-debug.log*",
	"yarn-debug.log*",
	"yarn-error.log*",
]
