#!/usr/bin/env node
const input = JSON.parse(require('fs').readFileSync(0, 'utf-8'));
console.log(JSON.stringify({
  shouldContinue: true,
  contextModification: "CONTEXT_INJECTION: User is in plan mode",
  errorMessage: ""
}));
