export const EXTERNAL_LINKS = {
	GITHUB: "https://github.com/RooCodeInc/Roo-Code",
	GITHUB_DISCUSSIONS: "https://github.com/RooCodeInc/Roo-Code/discussions",
	DISCORD: "https://discord.gg/roocode",
	REDDIT: "https://reddit.com/r/RooCode",
	X: "https://x.com/roo_code",
	LINKEDIN: "https://www.linkedin.com/company/roo-code",
	TIKTOK: "https://www.tiktok.com/@roo.code",
	BLUESKY: "https://bsky.app/profile/roocode.bsky.social",
	YOUTUBE: "https://www.youtube.com/@RooCodeYT",
	DOCUMENTATION: "https://docs.roocode.com",
	CAREERS: "https://careers.roocode.com",
	ISSUES: "https://github.com/RooCodeInc/Roo-Code/issues",
	FEATURE_REQUESTS: "https://github.com/RooCodeInc/Roo-Code/discussions/categories/feature-requests",
	COMMUNITY: "https://github.com/RooCodeInc/Roo-Code/discussions",
	CHANGELOG: "https://github.com/RooCodeInc/Roo-Code/blob/main/CHANGELOG.md",
	PRIVACY_POLICY_EXTENSION: "https://github.com/RooCodeInc/Roo-Code/blob/main/PRIVACY.md",
	INTEGRATIONS: "https://docs.roocode.com/community",
	TUTORIALS: "https://docs.roocode.com/tutorial-videos",
	MARKETPLACE: "https://marketplace.visualstudio.com/items?itemName=RooVeterinaryInc.roo-cline",
	SECURITY: "https://trust.roocode.com",
	EVALS: "https://roocode.com/evals",
	BLOG: "https://blog.roocode.com",
	OFFICE_HOURS_PODCAST: "https://www.youtube.com/@RooCodeYT/podcasts",
	FAQ: "https://roocode.com/#faq",
	TESTIMONIALS: "https://roocode.com/#testimonials",
}

export const INTERNAL_LINKS = {
	PRIVACY_POLICY_WEBSITE: "/privacy",
}
