name: Bug Report
description: Clearly report a bug with detailed repro steps
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for taking the time to fill out this bug report!**

        Please ensure this bug hasn't been reported already by searching existing [GitHub Issues](https://github.com/RooVetGit/Roo-Code/issues).
  - type: input
    id: version
    attributes:
      label: App Version
      description: Specify exactly which version you're using (e.g., v3.3.1)
    validations:
      required: true

  - type: dropdown
    id: provider
    attributes:
      label: API Provider
      description: Choose the API provider involved
      multiple: false
      options:
        - Anthropic
        - AWS Bedrock
        - Chutes AI
        - DeepSeek
        - Glama
        - Google Gemini
        - Groq
        - Human Relay Provider
        - LM Studio
        - Mistral AI
        - Ollama
        - OpenAI
        - OpenAI Compatible
        - OpenRouter
        - Requesty
        - Unbound
        - VS Code Language Model API
        - xAI (Grok)
        - Not Applicable / Other
    validations:
      required: true

  - type: input
    id: model
    attributes:
      label: Model Used
      description: Clearly specify the exact model (e.g., Claude 3.7 Sonnet). If not applicable, enter N/A.
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: Actual vs. Expected Behavior
      description: Clearly state what actually happened and what you expected instead.
      placeholder: Provide precise details of the issue here.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Detailed Steps to Reproduce
      description: |
        List the exact steps someone must follow to reproduce this bug:
        1. Starting conditions (software state, settings, environment)
        2. Precise actions taken (every click, selection, input)
        3. Clearly observe and report outcomes
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant API Request Output or Error Logs
      description: Paste relevant API logs, console outputs, or error messages here (formatted automatically as code).
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Include extra details, screenshots, or related issues.
