#!/usr/bin/env bun

import { readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
	BUILT_IN_PROVIDER_IDS,
	PROVIDER_ID_ALIASES,
} from "../src/providers/config/provider-ids";

interface ProviderModuleMetadata {
	providerId: string;
	moduleName: string;
	exportName: string;
}

const OUTPUT_FILE = "src/models/generated-provider-loaders.ts";
const PROVIDERS_DIR = "../src/models/catalog/providers";

function isModelCollection(
	value: unknown,
): value is { provider: { id: string } } {
	if (typeof value !== "object" || value === null) {
		return false;
	}
	const provider = (value as { provider?: unknown }).provider;
	if (typeof provider !== "object" || provider === null) {
		return false;
	}
	const providerId = (provider as { id?: unknown }).id;
	return typeof providerId === "string" && providerId.length > 0;
}

async function discoverProviderMetadata(): Promise<ProviderModuleMetadata[]> {
	const __filename = fileURLToPath(import.meta.url);
	const __dirname = dirname(__filename);
	const providersDir = join(__dirname, PROVIDERS_DIR);
	const providerFiles = readdirSync(providersDir)
		.filter((file) => file.endsWith(".ts") && file !== "index.ts")
		.sort((a, b) => a.localeCompare(b));

	const discovered: ProviderModuleMetadata[] = [];
	const discoveredProviderIds = new Set<string>();

	for (const providerFile of providerFiles) {
		const moduleName = providerFile.replace(/\.ts$/, "");
		const moduleUrl = new URL(
			`${PROVIDERS_DIR}/${providerFile}`,
			import.meta.url,
		).href;
		const moduleExports = (await import(moduleUrl)) as Record<string, unknown>;

		for (const [exportName, exportValue] of Object.entries(moduleExports)) {
			if (
				!exportName.endsWith("_PROVIDER") ||
				!isModelCollection(exportValue)
			) {
				continue;
			}

			const providerId = exportValue.provider.id;
			if (discoveredProviderIds.has(providerId)) {
				throw new Error(
					`Duplicate provider.id '${providerId}' discovered while generating loader registry.`,
				);
			}

			discovered.push({ providerId, moduleName, exportName });
			discoveredProviderIds.add(providerId);
		}
	}

	return discovered;
}

function addAliasEntries(
	moduleEntries: ProviderModuleMetadata[],
): ProviderModuleMetadata[] {
	const byProviderId = new Map<string, ProviderModuleMetadata>(
		moduleEntries.map((entry) => [entry.providerId, entry]),
	);

	const aliases: ProviderModuleMetadata[] = [];
	for (const [aliasId, canonicalId] of Object.entries(PROVIDER_ID_ALIASES)) {
		if (
			!BUILT_IN_PROVIDER_IDS.includes(
				aliasId as (typeof BUILT_IN_PROVIDER_IDS)[number],
			)
		) {
			continue;
		}
		if (byProviderId.has(aliasId)) {
			continue;
		}
		const canonical = byProviderId.get(canonicalId);
		if (!canonical) {
			throw new Error(
				`Provider alias '${aliasId}' points to '${canonicalId}', but no module metadata was discovered for that canonical provider.`,
			);
		}
		aliases.push({
			providerId: aliasId,
			moduleName: canonical.moduleName,
			exportName: canonical.exportName,
		});
	}

	return [...moduleEntries, ...aliases];
}

function validateCoverage(entries: ProviderModuleMetadata[]): void {
	const generatedIds = new Set(entries.map((entry) => entry.providerId));
	const missingBuiltIns = BUILT_IN_PROVIDER_IDS.filter(
		(providerId) => !generatedIds.has(providerId),
	);
	if (missingBuiltIns.length > 0) {
		throw new Error(
			`Generated provider loader registry is missing built-in provider IDs: ${missingBuiltIns.join(", ")}`,
		);
	}
}

export async function generateProviderLoaders(): Promise<void> {
	const discovered = await discoverProviderMetadata();
	const entries = addAliasEntries(discovered).sort((a, b) =>
		a.providerId.localeCompare(b.providerId),
	);

	validateCoverage(entries);

	const output = `/**
 * Auto-generated provider loader registry.
 *
 * WARNING: DO NOT EDIT THIS FILE MANUALLY.
 *
 * Generated by: @clinebot/llms/scripts/generate-provider-loaders.ts
 */

import type { ModelCollection } from "./types/index";

export type GeneratedProviderLoaderEntry = readonly [
  providerId: string,
  load: () => Promise<ModelCollection>,
];

export const GENERATED_PROVIDER_LOADER_ENTRIES: GeneratedProviderLoaderEntry[] = [
${entries
	.map(
		(entry) =>
			`  [\n    ${JSON.stringify(entry.providerId)},\n    async () => (await import("./catalog/providers/${entry.moduleName}")).${entry.exportName},\n  ],`,
	)
	.join("\n")}
];
`;

	const __filename = fileURLToPath(import.meta.url);
	const __dirname = dirname(__filename);
	const outputPath = join(__dirname, "..", OUTPUT_FILE);
	writeFileSync(outputPath, output, "utf8");

	console.log(`Generated ${OUTPUT_FILE}`);
	console.log(`Provider loaders: ${entries.length}`);
}

if (import.meta.main) {
	generateProviderLoaders().catch((error) => {
		console.error(error instanceof Error ? error.message : String(error));
		process.exitCode = 1;
	});
}
