#!/usr/bin/env bun

import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { ModelInfo } from "@cline/shared";
import {
	fetchClineRecommendedModelsPayload,
	normalizeClineRecommendedProviderModels,
} from "../src/catalog/catalog-cline-recommended";
import type { ModelsDevGeneratedProviderSpec } from "../src/catalog/catalog-live";
import { loadModelsDevCatalog } from "./models/generate-models-dev";
import { writeGeneratedFiles } from "./models/write-generated-files";

const MODEL_OUTPUT_FILE = "src/catalog/catalog.generated.ts";
const RECOMMENDED_OUTPUT_FILE = "src/catalog/cline-recommended.generated.ts";
const PROVIDER_OUTPUT_FILE = "src/providers/providers.generated.ts";
const PROVIDER_IDS_OUTPUT_FILE = "src/providers/provider-ids.generated.ts";

function sortObjectByKey<T>(
	input: Record<string, T>,
	order: "asc" | "desc" = "asc",
): Record<string, T> {
	return Object.fromEntries(
		Object.entries(input).sort(([a], [b]) =>
			order === "asc" ? a.localeCompare(b) : b.localeCompare(a),
		),
	);
}

function normalizeValue(value: unknown): unknown {
	if (Array.isArray(value)) {
		return value.map(normalizeValue);
	}
	if (value && typeof value === "object") {
		const objectValue = value as Record<string, unknown>;
		return Object.fromEntries(
			Object.entries(objectValue)
				.sort(([a], [b]) => a.localeCompare(b))
				.map(([key, nestedValue]) => [key, normalizeValue(nestedValue)]),
		);
	}
	return value;
}

function renderGeneratedProviderIds(
	generatedProviderIds: readonly string[],
): string {
	return `/**
 * Auto-generated provider identifiers.
 *
 * Generated by: @cline/llms/scripts/generate-models.ts
 *
 * This is only the models.dev-derived subset. Use BUILT_IN_PROVIDER_IDS from
 * ./ids.ts for the complete registry, including handwritten product and local
 * providers from ./builtins.ts.
 *
 * WARNING: DO NOT EDIT THIS FILE MANUALLY.
 */
export const GENERATED_PROVIDER_IDS = ${JSON.stringify(generatedProviderIds, null, 2)} as const;
`;
}

function renderGeneratedProviderSpecs(
	providerSpecs: Record<string, ModelsDevGeneratedProviderSpec>,
): string {
	const generatedProviderSpecs = Object.values(providerSpecs);
	return `/**
 * Auto-generated provider catalog.
 *
 * Generated by: @cline/llms/scripts/generate-models.ts
 *
 * To generate a models.dev provider, ensure its upstream entry uses an AI SDK
 * package supported by catalog-live.ts. Add an ID mapping in provider-keys.ts
 * when Cline's generated ID differs from the models.dev key, and ensure the ID
 * is not in MODELS_DEV_BLOCKED_PROVIDER_IDS. Then run:
 *   bun -F @cline/llms generate:models
 *
 * Product/runtime-only providers belong in builtins.ts and are merged with
 * this catalog; they do not need to appear in this generated file.
 *
 * WARNING: DO NOT EDIT THIS FILE MANUALLY.
 */
import type { BuiltinSpec } from "./builtin-types";

export const GENERATED_PROVIDER_SPECS: readonly BuiltinSpec[] = ${JSON.stringify(generatedProviderSpecs, null, 2)};
`;
}

async function generate(): Promise<void> {
	const __filename = fileURLToPath(import.meta.url);
	const __dirname = dirname(__filename);
	const root = join(__dirname, "..");
	const modelOutputPath = join(root, MODEL_OUTPUT_FILE);
	const providerOutputPath = join(root, PROVIDER_OUTPUT_FILE);
	const providerIdsOutputPath = join(root, PROVIDER_IDS_OUTPUT_FILE);

	const providerModels: Record<string, Record<string, ModelInfo>> = {};
	let providerSpecs: Record<string, ModelsDevGeneratedProviderSpec> = {};
	let loadError: Error | undefined;

	const [modelsDevResult, clineRecommendedPayloadResult] = await Promise.all([
		loadModelsDevCatalog().catch((error) => {
			loadError =
				error instanceof Error ? error : new Error(String(error ?? "unknown"));
			return {
				providerModels: {},
				providerSpecs: {},
			};
		}),
		fetchClineRecommendedModelsPayload(fetch).catch((error) => {
			loadError =
				error instanceof Error ? error : new Error(String(error ?? "unknown"));
			return undefined;
		}),
	]);

	// Never replace a complete offline snapshot with a partial network result.
	if (
		!clineRecommendedPayloadResult ||
		Object.keys(modelsDevResult.providerModels).length === 0 ||
		Object.keys(modelsDevResult.providerSpecs).length === 0
	) {
		throw new Error(
			`Aborting model generation: incomplete upstream catalogs (${loadError?.message ?? "empty response"}).`,
		);
	}

	const recommendedOutput = `/** Auto-generated by scripts/generate-models.ts. Do not edit manually. */
import type { ClineRecommendedModelsPayload } from "./catalog-cline-recommended";

export const GENERATED_CLINE_RECOMMENDED_MODELS: ClineRecommendedModelsPayload = ${JSON.stringify({ recommended: clineRecommendedPayloadResult.recommended ?? [], free: clineRecommendedPayloadResult.free ?? [], clinePass: clineRecommendedPayloadResult.clinePass ?? [] }, null, 2)};
`;

	Object.assign(providerModels, modelsDevResult.providerModels);
	providerSpecs = modelsDevResult.providerSpecs;

	Object.assign(
		providerModels,
		normalizeClineRecommendedProviderModels(
			clineRecommendedPayloadResult,
			providerModels.openrouter || {},
		),
	);

	const sortedProviders = sortObjectByKey(providerModels);
	const sortedProviderSpecs = sortObjectByKey(providerSpecs);
	const generatedModelsVersion = Date.now();
	const output = `/**
 * Auto-generated model catalog.
 *
 * Generated by: @cline/llms/scripts/generate-models.ts
 *
 * WARNING: DO NOT EDIT THIS FILE MANUALLY.
 */
import type { ModelInfo } from "@cline/shared";
/**
 * Model list auto-generated for built-in providers
 * listed in @cline/llms/src/providers/provider-keys.ts
*/
export const GENERATED_PROVIDER_MODELS: {
  version: number
  providers: Record<string, Record<string, ModelInfo>>
} = {
  version: ${JSON.stringify(generatedModelsVersion)},
  providers: ${JSON.stringify(sortedProviders, null, 2)}
}
`;
	let modelOutput = output;

	if (existsSync(modelOutputPath)) {
		const nextProviders = normalizeValue(sortedProviders);
		let existingProviders: unknown | undefined;
		try {
			const existingModule = (await import(
				"../src/catalog/catalog.generated.js"
			)) as {
				GENERATED_PROVIDER_MODELS?: {
					providers?: Record<string, Record<string, ModelInfo>>;
				};
			};
			existingProviders = existingModule.GENERATED_PROVIDER_MODELS?.providers;
		} catch {
			existingProviders = undefined;
		}
		if (
			existingProviders &&
			JSON.stringify(normalizeValue(existingProviders)) ===
				JSON.stringify(nextProviders)
		) {
			modelOutput = readFileSync(modelOutputPath, "utf8");
		}
	}

	writeGeneratedFiles(
		new Map([
			[join(root, RECOMMENDED_OUTPUT_FILE), recommendedOutput],
			[modelOutputPath, modelOutput],
			[providerOutputPath, renderGeneratedProviderSpecs(sortedProviderSpecs)],
			[
				providerIdsOutputPath,
				renderGeneratedProviderIds(
					Object.values(sortedProviderSpecs).map((spec) => spec.id),
				),
			],
		]),
	);

	const totalModels = Object.values(sortedProviders).reduce(
		(count, models) => count + Object.keys(models).length,
		0,
	);
	console.log(`Generated ${MODEL_OUTPUT_FILE}`);
	console.log(`Providers: ${Object.keys(sortedProviders).length}`);
	console.log(`Models: ${totalModels}`);
}

generate().catch((error) => {
	console.error(error instanceof Error ? error.message : String(error));
	process.exitCode = 1;
});
