#!/usr/bin/env bun

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { ModelInfo } from "@cline/shared";
import {
	fetchClineRecommendedModelsPayload,
	normalizeClineRecommendedProviderModels,
} from "../src/catalog/catalog-cline-recommended";
import type { ModelsDevGeneratedProviderSpec } from "../src/catalog/catalog-live";
import { loadModelsDevCatalog } from "./models/generate-models-dev";

const MODEL_OUTPUT_FILE = "src/catalog/catalog.generated.ts";
const PROVIDER_OUTPUT_FILE = "src/providers/providers.generated.ts";
const PROVIDER_IDS_OUTPUT_FILE = "src/providers/provider-ids.generated.ts";

function sortObjectByKey<T>(
	input: Record<string, T>,
	order: "asc" | "desc" = "asc",
): Record<string, T> {
	return Object.fromEntries(
		Object.entries(input).sort(([a], [b]) =>
			order === "asc" ? a.localeCompare(b) : b.localeCompare(a),
		),
	);
}

function normalizeValue(value: unknown): unknown {
	if (Array.isArray(value)) {
		return value.map(normalizeValue);
	}
	if (value && typeof value === "object") {
		const objectValue = value as Record<string, unknown>;
		return Object.fromEntries(
			Object.entries(objectValue)
				.sort(([a], [b]) => a.localeCompare(b))
				.map(([key, nestedValue]) => [key, normalizeValue(nestedValue)]),
		);
	}
	return value;
}

async function writeGeneratedProviderIds(
	outputPath: string,
	generatedProviderIds: readonly string[],
): Promise<void> {
	const output = `/**
 * Auto-generated provider identifiers.
 *
 * Generated by: @cline/llms/scripts/generate-models.ts
 *
 * WARNING: DO NOT EDIT THIS FILE MANUALLY.
 */
export const GENERATED_PROVIDER_IDS = ${JSON.stringify(generatedProviderIds, null, 2)} as const;
`;

	mkdirSync(dirname(outputPath), { recursive: true });

	if (existsSync(outputPath)) {
		if (readFileSync(outputPath, "utf8") === output) {
			console.log(`No changes detected for ${PROVIDER_IDS_OUTPUT_FILE}`);
			return;
		}
	}

	writeFileSync(outputPath, output, "utf8");
	console.log(`Generated ${PROVIDER_IDS_OUTPUT_FILE}`);
}

async function writeGeneratedProviderSpecs(
	outputPath: string,
	providerIdsOutputPath: string,
	providerSpecs: Record<string, ModelsDevGeneratedProviderSpec>,
): Promise<void> {
	if (Object.keys(providerSpecs).length === 0) {
		if (existsSync(outputPath)) {
			console.warn(
				`Skipping provider generation: no provider specs were loaded. Existing generated providers were left unchanged.`,
			);
			return;
		}
		throw new Error(
			"Aborting provider generation: no provider specs were loaded. No existing generated providers file was found.",
		);
	}

	const generatedProviderSpecs = Object.values(providerSpecs);
	const generatedProviderIds = generatedProviderSpecs.map((spec) => spec.id);
	const output = `/**
 * Auto-generated provider catalog.
 *
 * Generated by: @cline/llms/scripts/generate-models.ts
 *
 * WARNING: DO NOT EDIT THIS FILE MANUALLY.
 */
import type { BuiltinSpec } from "./builtin-types";

export const GENERATED_PROVIDER_SPECS: readonly BuiltinSpec[] = ${JSON.stringify(generatedProviderSpecs, null, 2)};
`;

	mkdirSync(dirname(outputPath), { recursive: true });
	await writeGeneratedProviderIds(providerIdsOutputPath, generatedProviderIds);

	if (existsSync(outputPath)) {
		if (readFileSync(outputPath, "utf8") === output) {
			console.log(`No changes detected for ${PROVIDER_OUTPUT_FILE}`);
			console.log(`Generated providers: ${generatedProviderSpecs.length}`);
			return;
		}
	}

	writeFileSync(outputPath, output, "utf8");
	console.log(`Generated ${PROVIDER_OUTPUT_FILE}`);
	console.log(`Generated providers: ${generatedProviderSpecs.length}`);
}

async function generate(): Promise<void> {
	const __filename = fileURLToPath(import.meta.url);
	const __dirname = dirname(__filename);
	const root = join(__dirname, "..");
	const modelOutputPath = join(root, MODEL_OUTPUT_FILE);
	const providerOutputPath = join(root, PROVIDER_OUTPUT_FILE);
	const providerIdsOutputPath = join(root, PROVIDER_IDS_OUTPUT_FILE);

	const providerModels: Record<string, Record<string, ModelInfo>> = {};
	let providerSpecs: Record<string, ModelsDevGeneratedProviderSpec> = {};
	let loadError: Error | undefined;

	const [modelsDevResult, clineRecommendedPayloadResult] = await Promise.all([
		loadModelsDevCatalog().catch((error) => {
			loadError =
				error instanceof Error ? error : new Error(String(error ?? "unknown"));
			return {
				providerModels: {},
				providerSpecs: {},
			};
		}),
		fetchClineRecommendedModelsPayload(fetch).catch((error) => {
			loadError =
				error instanceof Error ? error : new Error(String(error ?? "unknown"));
			return undefined;
		}),
	]);

	Object.assign(providerModels, modelsDevResult.providerModels);
	providerSpecs = modelsDevResult.providerSpecs;

	if (clineRecommendedPayloadResult) {
		Object.assign(
			providerModels,
			normalizeClineRecommendedProviderModels(
				clineRecommendedPayloadResult,
				providerModels.openrouter || {},
			),
		);
	}

	if (Object.keys(providerModels).length === 0) {
		const details = loadError?.message ?? "unknown error";
		if (existsSync(modelOutputPath)) {
			console.warn(
				`Skipping model generation: no provider models were loaded (${details}). Existing generated catalog was left unchanged.`,
			);
			return;
		}
		throw new Error(
			`Aborting model generation: no provider models were loaded (${details}). No existing generated catalog was found.`,
		);
	}

	const sortedProviders = sortObjectByKey(providerModels);
	const sortedProviderSpecs = sortObjectByKey(providerSpecs);
	const generatedModelsVersion = Date.now();
	const output = `/**
 * Auto-generated model catalog.
 *
 * Generated by: @cline/llms/scripts/generate-models.ts
 *
 * WARNING: DO NOT EDIT THIS FILE MANUALLY.
 */
import type { ModelInfo } from "@cline/shared";
/**
 * Model list auto-generated for built-in providers
 * listed in @cline/llms/src/providers/provider-keys.ts
*/
export const GENERATED_PROVIDER_MODELS: {
  version: number
  providers: Record<string, Record<string, ModelInfo>>
} = {
  version: ${JSON.stringify(generatedModelsVersion)},
  providers: ${JSON.stringify(sortedProviders, null, 2)}
}
`;
	mkdirSync(dirname(modelOutputPath), { recursive: true });

	if (existsSync(modelOutputPath)) {
		const nextProviders = normalizeValue(sortedProviders);
		let existingProviders: unknown | undefined;
		try {
			const existingModule = (await import(
				"../src/catalog/catalog.generated.js"
			)) as {
				GENERATED_PROVIDER_MODELS?: {
					providers?: Record<string, Record<string, ModelInfo>>;
				};
			};
			existingProviders = existingModule.GENERATED_PROVIDER_MODELS?.providers;
		} catch {
			existingProviders = undefined;
		}
		if (
			existingProviders &&
			JSON.stringify(normalizeValue(existingProviders)) ===
				JSON.stringify(nextProviders)
		) {
			await writeGeneratedProviderSpecs(
				providerOutputPath,
				providerIdsOutputPath,
				sortedProviderSpecs,
			);
			const totalModels = Object.values(sortedProviders).reduce(
				(count, models) => count + Object.keys(models).length,
				0,
			);
			console.log(`No changes detected for ${MODEL_OUTPUT_FILE}`);
			console.log(`Providers: ${Object.keys(sortedProviders).length}`);
			console.log(`Models: ${totalModels}`);
			return;
		}
	}

	writeFileSync(modelOutputPath, output, "utf8");

	await writeGeneratedProviderSpecs(
		providerOutputPath,
		providerIdsOutputPath,
		sortedProviderSpecs,
	);

	const totalModels = Object.values(sortedProviders).reduce(
		(count, models) => count + Object.keys(models).length,
		0,
	);
	console.log(`Generated ${MODEL_OUTPUT_FILE}`);
	console.log(`Providers: ${Object.keys(sortedProviders).length}`);
	console.log(`Models: ${totalModels}`);
}

generate().catch((error) => {
	console.error(error instanceof Error ? error.message : String(error));
	process.exitCode = 1;
});
