#!/usr/bin/env bun

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { ModelInfo } from "../src/models/types/index";
import { generateProviderLoaders } from "./generate-provider-loaders";
import { loadModelsDevProviderModels } from "./models/generate-models-dev";

const OUTPUT_FILE = "src/models/generated.ts";

function sortObjectByKey<T>(
	input: Record<string, T>,
	order: "asc" | "desc" = "asc",
): Record<string, T> {
	return Object.fromEntries(
		Object.entries(input).sort(([a], [b]) =>
			order === "asc" ? a.localeCompare(b) : b.localeCompare(a),
		),
	);
}

function normalizeValue(value: unknown): unknown {
	if (Array.isArray(value)) {
		return value.map(normalizeValue);
	}
	if (value && typeof value === "object") {
		const objectValue = value as Record<string, unknown>;
		return Object.fromEntries(
			Object.entries(objectValue)
				.sort(([a], [b]) => a.localeCompare(b))
				.map(([key, nestedValue]) => [key, normalizeValue(nestedValue)]),
		);
	}
	return value;
}

async function generate(): Promise<void> {
	await generateProviderLoaders();

	const __filename = fileURLToPath(import.meta.url);
	const __dirname = dirname(__filename);
	const root = join(__dirname, "..");
	const outputPath = join(root, OUTPUT_FILE);

	const providerModels: Record<string, Record<string, ModelInfo>> = {};
	let loadError: Error | undefined;

	try {
		const modelsDev = await loadModelsDevProviderModels();
		Object.assign(providerModels, modelsDev);
	} catch (error) {
		loadError =
			error instanceof Error ? error : new Error(String(error ?? "unknown"));
	}

	if (Object.keys(providerModels).length === 0) {
		const details = loadError?.message ?? "unknown error";
		if (existsSync(outputPath)) {
			console.warn(
				`Skipping model generation: no provider models were loaded (${details}). Existing generated catalog was left unchanged.`,
			);
			return;
		}
		throw new Error(
			`Aborting model generation: no provider models were loaded (${details}). No existing generated catalog was found.`,
		);
	}

	const sortedProviders = sortObjectByKey(providerModels);
	const generatedModelsVersion = Date.now();
	const output = `/**
 * Auto-generated model catalog.
 *
 * WARNING: DO NOT EDIT THIS FILE MANUALLY.
 *
 * Generated by: @clinebot/llms/scripts/generate-models.ts
 * Inputs:
 * - ./scripts/generate-models-dev.ts
 */

import type { ModelInfo } from "./types/index"

export const GENERATED_PROVIDER_MODELS: {
  version: number
  providers: Record<string, Record<string, ModelInfo>>
} = {
  version: ${JSON.stringify(generatedModelsVersion)},
  providers: ${JSON.stringify(sortedProviders, null, 2)}
}
`;
	mkdirSync(dirname(outputPath), { recursive: true });

	if (existsSync(outputPath)) {
		const nextProviders = normalizeValue(sortedProviders);
		let existingProviders: unknown | undefined;
		try {
			const existingModule = (await import("../src/models/generated.js")) as {
				GENERATED_PROVIDER_MODELS?: {
					providers?: Record<string, Record<string, ModelInfo>>;
				};
			};
			existingProviders = existingModule.GENERATED_PROVIDER_MODELS?.providers;
		} catch {
			existingProviders = undefined;
		}
		if (
			existingProviders &&
			JSON.stringify(normalizeValue(existingProviders)) ===
				JSON.stringify(nextProviders)
		) {
			const totalModels = Object.values(sortedProviders).reduce(
				(count, models) => count + Object.keys(models).length,
				0,
			);
			console.log(`No changes detected for ${OUTPUT_FILE}`);
			console.log(`Providers: ${Object.keys(sortedProviders).length}`);
			console.log(`Models: ${totalModels}`);
			return;
		}
	}

	writeFileSync(outputPath, output, "utf8");

	const totalModels = Object.values(sortedProviders).reduce(
		(count, models) => count + Object.keys(models).length,
		0,
	);
	console.log(`Generated ${OUTPUT_FILE}`);
	console.log(`Providers: ${Object.keys(sortedProviders).length}`);
	console.log(`Models: ${totalModels}`);
}

generate().catch((error) => {
	console.error(error instanceof Error ? error.message : String(error));
	process.exitCode = 1;
});
