#!/usr/bin/env node
const input = JSON.parse(require('fs').readFileSync(0, 'utf-8'));
const deleted = input.taskResume?.previousState?.conversationHistoryDeleted === 'true';

console.log(JSON.stringify({
  cancel: false,
  contextModification: deleted
    ? "TASK_CONTEXT: Some conversation history was truncated due to context window limits"
    : "",
  errorMessage: ""
}));
