// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by proto/build-proto.sh

// Import all method implementations
import { registerBrowserMethod } from "./index";
import { getBrowserConnectionInfo } from "./getBrowserConnectionInfo";

// Register all browser service methods
export function registerAllBrowserMethods(): void {
  // Register each method with the registry
  registerBrowserMethod("getBrowserConnectionInfo", getBrowserConnectionInfo);
}
