export const AUDIO_PROGRAM_CONFIG = {
	darwin: {
		command: "ffmpeg",
		fallbackPaths: ["/usr/local/bin/ffmpeg", "/opt/homebrew/bin/ffmpeg"],
		getArgs: (outputFile: string) => [
			"-f",
			"avfoundation",
			"-i",
			":default",
			"-c:a",
			"libopus",
			"-b:a",
			"32k",
			"-application",
			"voip",
			"-ar",
			"16000",
			"-ac",
			"1",
			outputFile,
		],
		error: "It looks like your system is missing the 'FFmpeg' utility, which is required for voice recording. To install it, please ensure you are in **Act Mode** and then send this message. I will handle the installation for you.\n\n**Installation command:** `brew install ffmpeg`",
	},
	linux: {
		command: "ffmpeg",
		fallbackPaths: ["/usr/bin/ffmpeg", "/usr/local/bin/ffmpeg"],
		getArgs: (outputFile: string) => [
			"-f",
			"alsa",
			"-i",
			"default",
			"-c:a",
			"libopus",
			"-b:a",
			"32k",
			"-application",
			"voip",
			"-ar",
			"16000",
			"-ac",
			"1",
			outputFile,
		],
		error: "It looks like your system is missing the 'FFmpeg' utility, which is required for voice recording. To install it, please ensure you are in **Act Mode** and then send this message. I will handle the installation for you.\n\n**Installation command:** `sudo apt-get install ffmpeg`",
	},
	win32: {
		command: "ffmpeg",
		fallbackPaths: ["C:\\ffmpeg\\bin\\ffmpeg.exe", "C:\\Program Files\\ffmpeg\\bin\\ffmpeg.exe"],
		getArgs: (outputFile: string) => [
			"-f",
			"wasapi",
			"-i",
			"audio=default",
			"-c:a",
			"libopus",
			"-b:a",
			"32k",
			"-application",
			"voip",
			"-ar",
			"16000",
			"-ac",
			"1",
			outputFile,
		],
		error: "It looks like your system is missing the 'FFmpeg' utility, which is required for voice recording. To install it, please ensure you are in **Act Mode** and then send this message. I will handle the installation for you.\n\n**Installation command:** `winget install Gyan.FFmpeg`",
	},
}
