export type CheckpointAction =
	| "shadow_git_initialized"
	| "commit_created"
	| "restored"
	| "diff_generated"
	| "git_not_installed"
	| "tracker_creation_failed"
	| "commit_failed"
	| "restore_failed"
	| "init_failed"
	| "worktree_config_failed"
	| "add_files_failed"
	| "exclude_file_failed"
	| "directory_creation_failed"
	| "workspace_access_failed"
