// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.19.1
// source: models.proto

/* eslint-disable */
import { StringArray, StringRequest } from "./common"

export const protobufPackage = "cline"

/** Service for model-related operations */
export type ModelsServiceDefinition = typeof ModelsServiceDefinition
export const ModelsServiceDefinition = {
	name: "ModelsService",
	fullName: "cline.ModelsService",
	methods: {
		/** Fetches available models from Ollama */
		getOllamaModels: {
			name: "getOllamaModels",
			requestType: StringRequest,
			requestStream: false,
			responseType: StringArray,
			responseStream: false,
			options: {},
		},
		/** Fetches available models from LM Studio */
		getLmStudioModels: {
			name: "getLmStudioModels",
			requestType: StringRequest,
			requestStream: false,
			responseType: StringArray,
			responseStream: false,
			options: {},
		},
	},
} as const
