// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.19.1
// source: system.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire"
import { Empty } from "./common"

export const protobufPackage = "cline"

export interface OpenUrlRequest {
	url: string
}

function createBaseOpenUrlRequest(): OpenUrlRequest {
	return { url: "" }
}

export const OpenUrlRequest: MessageFns<OpenUrlRequest> = {
	encode(message: OpenUrlRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
		if (message.url !== "") {
			writer.uint32(10).string(message.url)
		}
		return writer
	},

	decode(input: BinaryReader | Uint8Array, length?: number): OpenUrlRequest {
		const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
		let end = length === undefined ? reader.len : reader.pos + length
		const message = createBaseOpenUrlRequest()
		while (reader.pos < end) {
			const tag = reader.uint32()
			switch (tag >>> 3) {
				case 1: {
					if (tag !== 10) {
						break
					}

					message.url = reader.string()
					continue
				}
			}
			if ((tag & 7) === 4 || tag === 0) {
				break
			}
			reader.skip(tag & 7)
		}
		return message
	},

	fromJSON(object: any): OpenUrlRequest {
		return { url: isSet(object.url) ? globalThis.String(object.url) : "" }
	},

	toJSON(message: OpenUrlRequest): unknown {
		const obj: any = {}
		if (message.url !== "") {
			obj.url = message.url
		}
		return obj
	},

	create<I extends Exact<DeepPartial<OpenUrlRequest>, I>>(base?: I): OpenUrlRequest {
		return OpenUrlRequest.fromPartial(base ?? ({} as any))
	},
	fromPartial<I extends Exact<DeepPartial<OpenUrlRequest>, I>>(object: I): OpenUrlRequest {
		const message = createBaseOpenUrlRequest()
		message.url = object.url ?? ""
		return message
	},
}

export type SystemServiceDefinition = typeof SystemServiceDefinition
export const SystemServiceDefinition = {
	name: "SystemService",
	fullName: "cline.SystemService",
	methods: {
		openUrl: {
			name: "openUrl",
			requestType: OpenUrlRequest,
			requestStream: false,
			responseType: Empty,
			responseStream: false,
			options: {},
		},
	},
} as const

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined

export type DeepPartial<T> = T extends Builtin
	? T
	: T extends globalThis.Array<infer U>
		? globalThis.Array<DeepPartial<U>>
		: T extends ReadonlyArray<infer U>
			? ReadonlyArray<DeepPartial<U>>
			: T extends {}
				? { [K in keyof T]?: DeepPartial<T[K]> }
				: Partial<T>

type KeysOfUnion<T> = T extends T ? keyof T : never
export type Exact<P, I extends P> = P extends Builtin
	? P
	: P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never }

function isSet(value: any): boolean {
	return value !== null && value !== undefined
}

export interface MessageFns<T> {
	encode(message: T, writer?: BinaryWriter): BinaryWriter
	decode(input: BinaryReader | Uint8Array, length?: number): T
	fromJSON(object: any): T
	toJSON(message: T): unknown
	create<I extends Exact<DeepPartial<T>, I>>(base?: I): T
	fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T
}
