name = "aihydro-recognition"
main = "src/index.ts"
compatibility_date = "2026-05-29"
account_id = "01a127916c74d1e57bec43e48479cdfc"
workers_dev = true
preview_urls = false

[[d1_databases]]
binding = "DB"
database_name = "aihydro_recognition"
database_id = "0f043f39-f1e8-4d86-9ef3-eb6578898d47"
