#!/usr/bin/env python3
"""Generate the vendored ATIF JSON Schema from Harbor's Pydantic models.

ATIF has no published JSON Schema file. The normative definition is the RFC
plus the Pydantic models in the Harbor repository, so the schema used by the
tests in this package is generated from those models at a pinned commit.

Usage:
    git clone https://github.com/harbor-framework/harbor /tmp/harbor
    git -C /tmp/harbor checkout 0533a59c41ce435d9e59ff8c82da67f6e5b6edc7
    pip install pydantic
    python3 scripts/generate-atif-schema.py /tmp/harbor > src/atif/atif-v1.7.schema.json
    bun biome format --write src/atif/atif-v1.7.schema.json

Only the trajectory model modules are loaded; the rest of the Harbor package
(and its dependencies) is never imported.
"""

import json
import subprocess
import sys
import types
from pathlib import Path

HARBOR_REPOSITORY = "https://github.com/harbor-framework/harbor"
PINNED_COMMIT = "0533a59c41ce435d9e59ff8c82da67f6e5b6edc7"
ATIF_VERSION = "ATIF-v1.7"


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit("usage: generate-atif-schema.py <harbor-checkout>")
    checkout = Path(sys.argv[1]).resolve()
    commit = subprocess.run(
        ["git", "-C", str(checkout), "rev-parse", "HEAD"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()
    if commit != PINNED_COMMIT:
        sys.exit(f"harbor checkout is at {commit}, expected {PINNED_COMMIT}")

    src = checkout / "src" / "harbor"
    for name, path in (("harbor", src), ("harbor.models", src / "models")):
        module = types.ModuleType(name)
        module.__path__ = [str(path)]
        sys.modules[name] = module

    from harbor.models.trajectories import Trajectory  # noqa: E402

    schema = Trajectory.model_json_schema()
    schema = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": f"{HARBOR_REPOSITORY}/blob/{PINNED_COMMIT}/rfcs/0001-trajectory-format.md",
        "$comment": (
            f"{ATIF_VERSION}. Generated by scripts/generate-atif-schema.py from "
            f"{HARBOR_REPOSITORY} src/harbor/models/trajectories at commit "
            f"{PINNED_COMMIT} with Trajectory.model_json_schema(). Cross-field "
            "rules enforced by the Pydantic validators are checked in "
            "src/atif/atif-validate.ts."
        ),
        **schema,
    }
    json.dump(schema, sys.stdout, indent="\t", sort_keys=False)
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()
