#!/usr/bin/env node
const input = JSON.parse(require('fs').readFileSync(0, 'utf-8'));
const turn = input.postAssistantTurn;
console.log(JSON.stringify({
  cancel: false,
  contextModification: "turn=" + turn.turnNumber + " tools=" + turn.toolNames.length + " len=" + turn.assistantText.length,
  errorMessage: ""
}));
