#!/usr/bin/env node
const input = JSON.parse(require('fs').readFileSync(0, 'utf-8'));
console.log(JSON.stringify({
  shouldContinue: true,
  contextModification: `WORKSPACE_RULES: Tool ${input.preToolUse.toolName} requires review`,
  errorMessage: ""
}));
