const mockVSCodeDarkTheme = {
	"--vscode-editor-background": "#1E1E1E",
	"--vscode-editor-foreground": "#D4D4D4",
	"--vscode-sideBar-background": "#252526",
	"--vscode-sideBar-foreground": "#CCCCCC",
	"--vscode-editorGroup-border": "#454545",
	"--vscode-descriptionForeground": "#CCCCCC99",
	"--vscode-foreground": "#D4D4D4",
	"--vscode-button-background": "#007ACC",
	"--vscode-button-foreground": "#FFFFFF",
	"--vscode-button-hoverBackground": "#005A9E",
	"--vscode-button-separator": "#FFFFFF4D",
	"--vscode-button-secondaryBackground": "#383B3D",
	"--vscode-button-secondaryForeground": "#CCCCCC",
	"--vscode-button-secondaryHoverBackground": "#454545",
	"--vscode-textLink-foreground": "#6fc3df",
	"--vscode-textLink-activeForeground": "#9CCBFF",
	"--vscode-errorForeground": "#f48771",
	"--vscode-editorWidget-border": "#303031",
	"--vscode-editorError-foreground": "#f14c4c",
	"--vscode-diffEditor-removedTextBackground": "#9c353520",
	"--vscode-diffEditor-insertedTextBackground": "#9ccc6520",
	"--vscode-editor-font-family": 'Menlo, Monaco, "Courier New", monospace',
	"--vscode-editor-font-size": "12px",
	"--vscode-font-family": '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
	"--vscode-font-size": "13px",
	"--vscode-focusBorder": "#007ACC",
	"--vscode-input-border": "#6B6B6B",
	"--vscode-banner-background": "#007ACC",
	"--vscode-banner-foreground": "#FFFFFF",
	"--vscode-banner-iconForeground": "#FFFFFF",
	"--vscode-titleBar-inactiveForeground": "#BBBBBB",
	"--vscode-input-foreground": "#D4D4D4",
	"--vscode-input-background": "#383B3D",
	"--vscode-editor-line-height": "20px",
	"--vscode-input-placeholderForeground": "#A6A6A6",
	"--vscode-activityWarningBadge-background": "#F9C20B",
	"--vscode-badge-background": "#007ACC",
	"--vscode-badge-foreground": "#FFFFFF",
	"--vscode-charts-green": "#73C991",
	"--vscode-charts-yellow": "#F9C20B",
	"--vscode-charts-red": "#F14C4C",
	"--vscode-menu-background": "#252526",
	"--vscode-menu-border": "#454545",
	"--vscode-menu-foreground": "#CCCCCC",
	"--vscode-menu-shadow": "#00000050",
	"--vscode-menu-selectionBackground": "#062F4A",
	"--vscode-menu-selectionForeground": "#FFFFFF",
	"--vscode-inputValidation-errorBackground": "#eb1424",
	"--vscode-inputValidation-errorForeground": "#fcd1c1",
	"--vscode-editor-foldBackground": "#252526",
	"--vscode-editor-foldPlaceholderForeground": "#454545",
	"--vscode-list-activeSelectionBackground": "#094771",
	"--vscode-list-activeSelectionForeground": "#FFFFFF",
	"--vscode-list-hoverBackground": "#2D2D30",
	"--vscode-editor-border": "#454545",
	"--vscode-textCodeBlock-background": "#3E3E42",
	"--vscode-toolbar-background": "#252526",
	"--vscode-toolbar-hoverBackground": "#3E3E42",
	"--vscode-widget-shadow": "#00000050",
	"--vscode-panel-border": "#454545",
	"--vscode-icon-foreground": "#CCCCCC",
	"--popover-foreground": "#D4D4D4",
	"--vscode-problemsErrorIcon-foreground": "#be1100",
}

const mockVSCodeLightTheme = {
	"--vscode-editor-background": "#FFFFFF",
	"--vscode-editor-foreground": "#000000",
	"--vscode-sideBar-background": "#F3F3F3",
	"--vscode-sideBar-foreground": "#3E3E42",
	"--vscode-editorGroup-border": "#D4D4D4",
	"--vscode-descriptionForeground": "#6F6F6F",
	"--vscode-foreground": "#000000",
	"--vscode-button-background": "#007ACC",
	"--vscode-button-foreground": "#FFFFFF",
	"--vscode-button-hoverBackground": "#005A9E",
	"--vscode-button-separator": "#0000001F",
	"--vscode-button-secondaryBackground": "#E8E8E8",
	"--vscode-button-secondaryForeground": "#3E3E42",
	"--vscode-button-secondaryHoverBackground": "#D5D5D5",
	"--vscode-textLink-foreground": "#6fc3df",
	"--vscode-textLink-activeForeground": "#0078D4",
	"--vscode-errorForeground": "#c72e0f",
	"--vscode-editorWidget-border": "#D4D4D4",
	"--vscode-editorError-foreground": "#c72e0f",
	"--vscode-diffEditor-removedTextBackground": "#c72e0f20",
	"--vscode-diffEditor-insertedTextBackground": "#36943220",
	"--vscode-editor-font-family": 'Menlo, Monaco, "Courier New", monospace',
	"--vscode-editor-font-size": "12px",
	"--vscode-font-family": '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
	"--vscode-font-size": "13px",
	"--vscode-focusBorder": "#007ACC",
	"--vscode-input-border": "#CECECE",
	"--vscode-banner-background": "#007ACC",
	"--vscode-banner-foreground": "#FFFFFF",
	"--vscode-banner-iconForeground": "#FFFFFF",
	"--vscode-titleBar-inactiveForeground": "#919191",
	"--vscode-input-foreground": "#000000",
	"--vscode-input-background": "#FFFFFF",
	"--vscode-editor-line-height": "20px",
	"--vscode-input-placeholderForeground": "#767676",
	"--vscode-activityWarningBadge-background": "#F9C20B",
	"--vscode-badge-background": "#007ACC",
	"--vscode-badge-foreground": "#FFFFFF",
	"--vscode-charts-green": "#73C991",
	"--vscode-charts-yellow": "#F9C20B",
	"--vscode-menu-background": "#F3F3F3",
	"--vscode-menu-border": "#D4D4D4",
	"--vscode-menu-foreground": "#6F6F6F",
	"--vscode-menu-shadow": "#00000029",
	"--vscode-menu-selectionBackground": "#007ACC",
	"--vscode-menu-selectionForeground": "#FFFFFF",
	"--vscode-inputValidation-errorBackground": "#f48771",
	"--vscode-inputValidation-errorForeground": "#c72e0f",
	"--vscode-list-activeSelectionBackground": "#094771",
	"--vscode-list-activeSelectionForeground": "#FFFFFF",
	"--vscode-list-hoverBackground": "#F0F0F0",
	"--vscode-editor-border": "#D4D4D4",
	"--vscode-textCodeBlock-background": "#F5F5F5",
	"--vscode-toolbar-background": "#F3F3F3",
	"--vscode-toolbar-hoverBackground": "#E8E8E8",
	"--vscode-widget-shadow": "#00000033",
	"--vscode-panel-border": "#D4D4D4",
	"--vscode-icon-foreground": "#3E3E42",
	"--popover-foreground": "#D4D4D4",
}

// Mock VSCode theme variables for Storybook
export const StorybookThemes = {
	dark: mockVSCodeDarkTheme,
	light: mockVSCodeLightTheme,
}
