package common

// WE WILL HAVE TO MIGRATE THIS FROM DATA TO v1 LATER
const SETTINGS_SUBFOLDER = "data"

const DEFAULT_CLINE_CORE_PORT = 50052

const DEFAULT_CLINE_MCP_SETTINGS_FILE = "cline_mcp_settings.json"
