// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by proto/build-proto.js

// Import all method implementations
import { accountLoginClicked } from "./accountLoginClicked"
import { accountLogoutClicked } from "./accountLogoutClicked"
import { authStateChanged } from "./authStateChanged"
import { getOrganizationCredits } from "./getOrganizationCredits"
import { getUserCredits } from "./getUserCredits"
import { getUserOrganizations } from "./getUserOrganizations"
import { registerMethod } from "./index"
import { setUserOrganization } from "./setUserOrganization"
import { subscribeToAuthStatusUpdate } from "./subscribeToAuthStatusUpdate"

// Streaming methods for this service
export const streamingMethods = ["subscribeToAuthStatusUpdate"]

// Register all account service methods
export function registerAllMethods(): void {
	// Register each method with the registry
	registerMethod("accountLoginClicked", accountLoginClicked)
	registerMethod("accountLogoutClicked", accountLogoutClicked)
	registerMethod("authStateChanged", authStateChanged)
	registerMethod("getOrganizationCredits", getOrganizationCredits)
	registerMethod("getUserCredits", getUserCredits)
	registerMethod("getUserOrganizations", getUserOrganizations)
	registerMethod("setUserOrganization", setUserOrganization)
	registerMethod("subscribeToAuthStatusUpdate", subscribeToAuthStatusUpdate, { isStreaming: true })
}
