import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const packageRoot = join(import.meta.dir, "..");
const palettePath = join(packageRoot, "theme", "palette.css");
const tokensPath = join(packageRoot, "theme", "tokens.css");
const themePath = join(packageRoot, "theme", "theme.css");
const scopedOutputPath = join(packageRoot, "theme", "scoped-tokens.css");
const componentThemeOutputPath = join(
	packageRoot,
	"theme",
	"component-theme.css",
);
const checkOnly = process.argv.includes("--check");
const scopedHeader = `/*
 * Generated by scripts/generate-theme.ts from theme/palette.css and
 * theme/tokens.css. Edit those sources, then run \`bun run generate:theme\`.
 */

`;
const componentThemeHeader = `/*
 * Generated by scripts/generate-theme.ts from theme/tokens.css and
 * theme/theme.css. Edit those sources, then run \`bun run generate:theme\`.
 *
 * These package-specific names keep embedded components from changing generic
 * host utilities such as bg-background, text-foreground, and rounded-lg.
 */

`;
const paletteImport = '@import "@cline/ui/theme/palette.css";';

function stripContractComment(source: string, sourcePath: string): string {
	const withoutHeader = source.replace(/^\/\*[\s\S]*?\*\/\s*/, "");
	if (withoutHeader === source) {
		throw new Error(`${sourcePath} must start with a contract comment`);
	}
	return withoutHeader.trim();
}

function replaceSelectorOnce(
	source: string,
	selector: string,
	replacement: string,
	sourcePath: string,
): string {
	const escapedSelector = selector.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
	const ruleStart = new RegExp(`^${escapedSelector} \\{`, "gm");
	if ((source.match(ruleStart) ?? []).length !== 1) {
		throw new Error(`${ruleStart} must occur exactly once in ${sourcePath}`);
	}
	return source.replace(ruleStart, `${replacement} {`);
}

function readBlock(source: string, selector: string): string {
	const start = source.indexOf(`${selector} {`);
	if (start < 0) throw new Error(`Missing ${selector} block`);
	const bodyStart = source.indexOf("{", start) + 1;
	let depth = 1;
	for (let index = bodyStart; index < source.length; index += 1) {
		if (source[index] === "{") depth += 1;
		if (source[index] === "}") depth -= 1;
		if (depth === 0) return source.slice(bodyStart, index);
	}
	throw new Error(`Unclosed ${selector} block`);
}

function declarationNames(source: string): string[] {
	return Array.from(
		source.matchAll(/(^|\n)\s*(--[a-z0-9-]+)\s*:/g),
		(match) => match[2],
	);
}

function componentThemeName(rawName: string): string {
	if (rawName.startsWith("--font-weight-")) {
		return rawName.replace("--font-weight-", "--font-weight-cline-ui-");
	}
	if (rawName.startsWith("--font-")) {
		return rawName.replace("--font-", "--font-cline-ui-");
	}
	if (rawName.startsWith("--text-")) {
		const [size, ...companions] = rawName.slice("--text-".length).split("--");
		return `--text-cline-ui-${size}${companions.length ? `--${companions.join("--")}` : ""}`;
	}
	throw new Error(`Unsupported component typography token ${rawName}`);
}

function mappedDeclaration(mappedName: string, rawName: string): string {
	const declaration = `\t${mappedName}: var(${rawName});`;
	return declaration.length < 80
		? declaration
		: `\t${mappedName}: var(\n\t\t${rawName}\n\t);`;
}

function generateComponentTheme(tokens: string, theme: string): string {
	const themeNames = declarationNames(readBlock(theme, "@theme inline"));
	const colorNames = themeNames.filter((name) => name.startsWith("--color-"));
	const radiusNames = themeNames.filter((name) => name.startsWith("--radius-"));
	const typographyNames = declarationNames(readBlock(tokens, ":root")).filter(
		(name) =>
			name.startsWith("--font-") ||
			name.startsWith("--font-weight-") ||
			name.startsWith("--text-"),
	);

	const declarations = [
		...colorNames.map((name) => {
			const rawName = name.replace("--color-", "--");
			return mappedDeclaration(
				name.replace("--color-", "--color-cline-ui-"),
				rawName,
			);
		}),
		"",
		...typographyNames.map((name) =>
			mappedDeclaration(componentThemeName(name), name),
		),
		"",
		...radiusNames.map((name) =>
			mappedDeclaration(name.replace("--radius-", "--radius-cline-ui-"), name),
		),
	];

	return `${componentThemeHeader}@custom-variant cline-ui-dark (&:is(.dark *));\n\n@theme inline {\n${declarations.join("\n")}\n}\n`;
}

function scopeVariableBlocks(source: string, sourcePath: string): string {
	const sharedSelector = ":root,\n.dark";
	const scopedSharedSelector =
		".cline-ui-theme,\n.dark .cline-ui-theme,\n.cline-ui-theme.dark";
	const withSharedScope = source.includes(`${sharedSelector} {`)
		? replaceSelectorOnce(
				source,
				sharedSelector,
				scopedSharedSelector,
				sourcePath,
			)
		: source;
	return replaceSelectorOnce(
		replaceSelectorOnce(
			withSharedScope,
			":root",
			".cline-ui-theme",
			sourcePath,
		),
		".dark",
		".dark .cline-ui-theme,\n.cline-ui-theme.dark",
		sourcePath,
	);
}

const paletteSource = stripContractComment(
	readFileSync(palettePath, "utf8"),
	palettePath,
);
const tokensSource = stripContractComment(
	readFileSync(tokensPath, "utf8"),
	tokensPath,
);
if (!tokensSource.startsWith(paletteImport)) {
	throw new Error(`${tokensPath} must import ${paletteImport}`);
}
const tokensWithoutPaletteImport = tokensSource
	.slice(paletteImport.length)
	.trim();
const theme = readFileSync(themePath, "utf8");
const generatedScopedTokens =
	scopedHeader +
	scopeVariableBlocks(paletteSource, palettePath) +
	"\n\n" +
	scopeVariableBlocks(tokensWithoutPaletteImport, tokensPath) +
	"\n";
const generatedComponentTheme = generateComponentTheme(
	tokensWithoutPaletteImport,
	theme,
);
const outputs = [
	[scopedOutputPath, generatedScopedTokens],
	[componentThemeOutputPath, generatedComponentTheme],
] as const;

if (checkOnly) {
	for (const [outputPath, generated] of outputs) {
		if (readFileSync(outputPath, "utf8") !== generated) {
			throw new Error(`${outputPath} is out of date`);
		}
	}
	console.log("@cline/ui generated theme files are current");
} else {
	for (const [outputPath, generated] of outputs) {
		writeFileSync(outputPath, generated);
	}
	console.log("Generated @cline/ui scoped and component themes");
}
