import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const packageRoot = join(import.meta.dir, "..");
const sourcePath = join(packageRoot, "theme", "tokens.css");
const outputPath = join(packageRoot, "theme", "scoped-tokens.css");
const checkOnly = process.argv.includes("--check");
const generatedHeader = `/*
 * Generated by scripts/generate-theme.ts from theme/tokens.css.
 * Edit tokens.css, then run \`bun run generate:theme\`.
 */

`;

function replaceSelector(
	source: string,
	selector: string,
	replacement: string,
): string {
	const ruleStart = `${selector} {`;
	if (source.split(ruleStart).length !== 2) {
		throw new Error(`${ruleStart} must occur exactly once in ${sourcePath}`);
	}
	return source.replace(ruleStart, `${replacement} {`);
}

const source = readFileSync(sourcePath, "utf8");
const sourceWithoutHeader = source.replace(/^\/\*[\s\S]*?\*\/\s*/, "");
if (sourceWithoutHeader === source) {
	throw new Error(`${sourcePath} must start with a contract comment`);
}
const generated =
	generatedHeader +
	replaceSelector(
		replaceSelector(sourceWithoutHeader, ":root", ".cline-ui-theme"),
		".dark",
		".dark .cline-ui-theme,\n.cline-ui-theme.dark",
	);

if (checkOnly) {
	if (readFileSync(outputPath, "utf8") !== generated) {
		throw new Error(`${outputPath} is out of date`);
	}
	console.log("@cline/ui generated theme file is current");
} else {
	writeFileSync(outputPath, generated);
	console.log("Generated @cline/ui scoped theme");
}
