import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

const packageRoot = join(import.meta.dir, "..");
const readThemeFile = (name: string) =>
	readFileSync(join(packageRoot, "theme", name), "utf8");

const palette = readThemeFile("palette.css");
const tokens = readThemeFile("tokens.css");
const tokensWithoutComments = tokens.replace(/\/\*[\s\S]*?\*\//g, "");
const paletteWithoutComments = palette.replace(/\/\*[\s\S]*?\*\//g, "");
const scopedTokens = readThemeFile("scoped-tokens.css");
const theme = readThemeFile("theme.css");
const componentTheme = readThemeFile("component-theme.css");
const base = readThemeFile("base.css");
const index = readThemeFile("index.css");
const components = readFileSync(join(packageRoot, "components.css"), "utf8");
const manifest = JSON.parse(
	readFileSync(join(packageRoot, "package.json"), "utf8"),
) as { exports?: Record<string, string> };

const requiredTokens = [
	"--background",
	"--foreground",
	"--primary",
	"--border",
	"--font-sans",
	"--font-mono",
	"--font-weight-normal",
	"--text-xs",
	"--text-6xl",
	"--sidebar",
	"--surface-1",
	"--text-1",
	"--border-1",
	"--success-surface",
	"--warning-surface",
	"--error-surface",
	"--info-surface",
];

for (const token of requiredTokens) {
	if (!tokens.includes(`${token}:`)) {
		throw new Error(`tokens.css is missing ${token}`);
	}
}

for (const paletteName of [
	"neutral",
	"accent",
	"error",
	"success",
	"warning",
	"info",
]) {
	for (let step = 1; step <= 12; step += 1) {
		for (const token of [
			`--${paletteName}-${step}:`,
			`--${paletteName}-a${step}:`,
		]) {
			if (palette.split(token).length !== 3) {
				throw new Error(`palette.css must define ${token} once per mode`);
			}
		}
	}
}

if (
	palette.includes("--cline-") ||
	tokens.includes("--cline-") ||
	theme.includes("--cline-") ||
	base.includes("--cline-")
) {
	throw new Error("theme contract must not expose --cline-* variables");
}
if (
	/@(?:apply|custom-variant|layer|theme|supports|media)\b/.test(
		paletteWithoutComments + tokensWithoutComments,
	)
) {
	throw new Error("palette.css and tokens.css must remain framework-neutral");
}
if (!tokensWithoutComments.includes('@import "@cline/ui/theme/palette.css";')) {
	throw new Error("tokens.css must import the owned palette");
}
if (
	/--(?:slate|violet|ruby|green|amber|sky)-(?:a)?\d+:/.test(palette) ||
	/@import/.test(scopedTokens) ||
	/(^|\n):root\s*\{/.test(scopedTokens)
) {
	throw new Error("owned palette names and scoped theme isolation must hold");
}
if (theme.includes("tokens.css") || !theme.includes("@theme inline")) {
	throw new Error(
		"theme.css must contain only the Tailwind mapping and variants",
	);
}
if (
	!componentTheme.includes("Generated by scripts/generate-theme.ts") ||
	!componentTheme.includes("@custom-variant cline-ui-dark") ||
	!componentTheme.includes("@theme inline") ||
	componentTheme.includes("@custom-variant dark ")
) {
	throw new Error(
		"component-theme.css must contain the generated namespaced Tailwind contract",
	);
}
if (!components.includes('@import "./theme/component-theme.css";')) {
	throw new Error("components.css must import the namespaced component theme");
}
if (base.includes("#__next") || base.includes("@source")) {
	throw new Error("base.css must not contain consumer-specific shell policy");
}
if (
	!index.includes('@import "@cline/ui/theme/tokens.css";') ||
	!index.includes('@import "@cline/ui/theme/theme.css";') ||
	!index.includes('@import "@cline/ui/theme/base.css";')
) {
	throw new Error("theme entry point must compose tokens, theme, and base CSS");
}
for (const subpath of [
	"./components.css",
	"./components/markdown.css",
	"./theme/index.css",
	"./theme/palette.css",
	"./theme/scoped-tokens.css",
	"./theme/tokens.css",
	"./theme/theme.css",
	"./theme/base.css",
]) {
	const target = manifest.exports?.[subpath];
	if (!target || !existsSync(join(packageRoot, target))) {
		throw new Error(`package.json export ${subpath} is missing or invalid`);
	}
}

console.log("@cline/ui theme contract is valid");
