import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

const packageRoot = join(import.meta.dir, "..");
const readThemeFile = (name: string) =>
	readFileSync(join(packageRoot, "theme", name), "utf8");
const readComponentFile = (name: string) =>
	readFileSync(join(packageRoot, "components", name), "utf8");

const tokens = readThemeFile("tokens.css");
const scopedTokens = readThemeFile("scoped-tokens.css");
const tokensWithoutComments = tokens.replace(/\/\*[\s\S]*?\*\//g, "");
const theme = readThemeFile("theme.css");
const base = readThemeFile("base.css");
const index = readThemeFile("index.css");
const markdown = readComponentFile("markdown.css");
const manifest = JSON.parse(
	readFileSync(join(packageRoot, "package.json"), "utf8"),
) as {
	exports?: Record<string, string | { import?: string; types?: string }>;
};

const requiredTokens = [
	"--background",
	"--foreground",
	"--primary",
	"--border",
	"--font-sans",
	"--font-mono",
	"--font-weight-normal",
	"--text-xs",
	"--text-6xl",
	"--sidebar",
];

for (const token of requiredTokens) {
	if (!tokens.includes(`${token}:`)) {
		throw new Error(`tokens.css is missing ${token}`);
	}
}

if (
	tokens.includes("--cline-") ||
	theme.includes("--cline-") ||
	base.includes("--cline-")
) {
	throw new Error("theme contract must not expose --cline-* variables");
}
if (/@(?:apply|custom-variant|layer|theme)\b/.test(tokensWithoutComments)) {
	throw new Error("tokens.css must remain framework-neutral");
}
if (!tokens.includes("Canonical Cline web theme tokens")) {
	throw new Error("tokens.css must remain the canonical token source");
}
if (!scopedTokens.includes("Generated by scripts/generate-theme.ts")) {
	throw new Error("scoped-tokens.css must be generated from tokens.css");
}
if (theme.includes("tokens.css") || !theme.includes("@theme inline")) {
	throw new Error(
		"theme.css must contain only the Tailwind mapping and variants",
	);
}
if (base.includes("#__next") || base.includes("@source")) {
	throw new Error("base.css must not contain consumer-specific shell policy");
}
if (!base.includes('@import "../components/markdown.css";')) {
	throw new Error(
		"base.css must compose the optional Markdown component styles",
	);
}
if (markdown.includes("@apply")) {
	throw new Error("components/markdown.css must remain framework-neutral");
}
if (
	!index.includes('@import "./tokens.css";') ||
	!index.includes('@import "./theme.css";') ||
	!index.includes('@import "./base.css";')
) {
	throw new Error("theme entry point must compose tokens, theme, and base CSS");
}
for (const subpath of [
	".",
	"./components.css",
	"./components/markdown.css",
	"./theme/index.css",
	"./theme/scoped-tokens.css",
	"./theme/tokens.css",
	"./theme/theme.css",
	"./theme/base.css",
]) {
	const exported = manifest.exports?.[subpath];
	const targets =
		typeof exported === "string"
			? [exported]
			: typeof exported === "object" && exported !== null
				? Object.values(exported).filter(
						(target): target is string => typeof target === "string",
					)
				: [];
	if (
		targets.length === 0 ||
		targets.some((target) => !existsSync(join(packageRoot, target)))
	) {
		throw new Error(`package.json export ${subpath} is missing or invalid`);
	}
}

console.log("@cline/ui theme contract is valid");
