export { resolveExistingFilePath } from "./path-resolution";
export {
	AGENT_CONFIG_DIRECTORY_NAME,
	AGENTS_RULES_FILE_NAME,
	CLINE_CHAT_WORKSPACE_DIRECTORY_NAME,
	CLINE_CONNECTOR_SETTINGS_FILE_NAME,
	CLINE_MCP_SETTINGS_FILE_NAME,
	CLINE_WORKSPACES_DIRECTORY_NAME,
	type CronSpecsScope,
	discoverPluginModulePaths,
	ensureFileExists,
	ensureHookLogDir,
	ensureParentDir,
	getPluginDisplayName,
	HOOKS_CONFIG_DIRECTORY_NAME,
	isChatWorkspacePath,
	isPluginModulePath,
	type ResolveCronSpecsDirOptions,
	type ResolveTaskSpecsDirOptions,
	RULES_CONFIG_DIRECTORY_NAME,
	resolveAgentConfigSearchPaths,
	resolveAgentsConfigDirPath,
	resolveChatWorkspacePath,
	resolveClineDataDir,
	resolveClineDir,
	resolveConfiguredPluginModulePaths,
	resolveConnectorDataDir,
	resolveConnectorLogPath,
	resolveConnectorSettingsPath,
	resolveConnectorsDbPath,
	resolveCronDbPath,
	resolveCronEventsDir,
	resolveCronReportsDir,
	resolveCronSpecsDir,
	resolveDbDataDir,
	resolveDocumentsClineDirectoryPath,
	resolveDocumentsExtensionPath,
	resolveGlobalAgentsRulesPath,
	resolveGlobalCronSpecsDir,
	resolveGlobalSettingsPath,
	resolveGlobalTaskSpecsDir,
	resolveHooksConfigSearchPaths,
	resolveMcpSettingsPath,
	resolvePluginConfigSearchPaths,
	resolvePluginModuleEntries,
	resolveProviderSettingsPath,
	resolveRulesConfigSearchPaths,
	resolveSessionDataDir,
	resolveSkillsConfigSearchPaths,
	resolveTaskSpecsDir,
	resolveTasksDbPath,
	resolveTeamDataDir,
	resolveWorkflowsConfigSearchPaths,
	resolveWorkspaceCronSpecsDir,
	resolveWorkspaceTaskSpecsDir,
	SKILLS_CONFIG_DIRECTORY_NAME,
	setClineDir,
	setClineDirIfUnset,
	setHomeDir,
	setHomeDirIfUnset,
	type TaskSpecsScope,
	WORKFLOWS_CONFIG_DIRECTORY_NAME,
} from "./paths";
