export { resolveExistingFilePath } from "./path-resolution";
export {
	AGENT_CONFIG_DIRECTORY_NAME,
	AGENT_PLUGIN_MANIFEST_FILE_NAME,
	AGENTS_RULES_FILE_NAME,
	CLINE_CHAT_WORKSPACE_DIRECTORY_NAME,
	CLINE_CONNECTOR_SETTINGS_FILE_NAME,
	CLINE_MCP_SETTINGS_FILE_NAME,
	CLINE_WORKSPACES_DIRECTORY_NAME,
	type CronSpecsScope,
	discoverPluginModulePaths,
	ensureFileExists,
	ensureHookLogDir,
	ensureParentDir,
	extractWorkspaceLayerPaths,
	getPluginDisplayName,
	HOOKS_CONFIG_DIRECTORY_NAME,
	isAgentPluginDirectory,
	isChatWorkspacePath,
	isPluginModulePath,
	type ResolveCronSpecsDirOptions,
	type ResolveTaskSpecsDirOptions,
	RULES_CONFIG_DIRECTORY_NAME,
	type WorkspacePathOrLayers,
	resolveAgentConfigSearchPaths,
	resolveAgentPluginSearchPaths,
	resolveAgentSchedulesDir,
	resolveAgentsConfigDirPath,
	resolveChatWorkspacePath,
	resolveClineDataDir,
	resolveClineDir,
	resolveConfiguredPluginModulePaths,
	resolveConnectorDataDir,
	resolveConnectorLogPath,
	resolveConnectorSettingsPath,
	resolveConnectorsDbPath,
	resolveCronDbPath,
	resolveCronEventsDir,
	resolveCronReportsDir,
	resolveCronSpecsDir,
	resolveDbDataDir,
	resolveDocumentsClineDirectoryPath,
	resolveDocumentsExtensionPath,
	resolveGlobalAgentsRulesPath,
	resolveGlobalCronSpecsDir,
	resolveGlobalRulesConfigPaths,
	resolveGlobalSettingsPath,
	resolveGlobalTaskSpecsDir,
	resolveHooksConfigSearchPaths,
	resolveMcpSettingsPath,
	resolvePluginConfigSearchPaths,
	resolvePluginModuleEntries,
	resolveProviderSettingsPath,
	resolveRulesConfigSearchPaths,
	resolveSessionDataDir,
	resolveSkillsConfigSearchPaths,
	resolveTaskSpecsDir,
	resolveTasksDbPath,
	resolveTeamDataDir,
	resolveWorkflowsConfigSearchPaths,
	resolveWorkspaceCronSpecsDir,
	resolveWorkspaceRulesConfigPaths,
	resolveWorkspaceTaskSpecsDir,
	SKILLS_CONFIG_DIRECTORY_NAME,
	setClineDir,
	setClineDirIfUnset,
	setHomeDir,
	setHomeDirIfUnset,
	type TaskSpecsScope,
	WORKFLOWS_CONFIG_DIRECTORY_NAME,
} from "./paths";
export {
	DEFAULT_WORKSPACE_PROJECT_RULES,
	initializeWorkspaceLayout,
	type InitializeWorkspaceLayoutOptions,
	type InitializeWorkspaceLayoutResult,
} from "./workspace-scaffold";
export {
	CLINE_BOUNDARY_FILE_NAME,
	CLINE_IGNORE_FILE_NAME,
	findWorkspaceHierarchy,
	findWorkspaceHierarchySync,
	findWorkspaceTraversalStop,
	globToRegExp,
	hasBoundaryMarkerFile,
	hasIsolationBoundary,
	isFileSystemRoot,
	loadClineIgnorePatternsSync,
	loadWorkspaceConfigSync,
	matchesAnyGlob,
	matchesGlob,
	type PathDirName,
	type ResolvedHierarchicalWorkspace,
	type ResolveWorkspaceOptions,
	resolveHierarchicalWorkspace,
	resolveHierarchicalWorkspaceSync,
	WORKSPACE_CONFIG_FILE_NAME,
	type WorkspaceConfig,
	WorkspaceConfigSchema,
	type WorkspaceLayer,
	type WorkspaceTraversalStop,
	type WorkspaceTraversalStopInput,
} from "./workspace";
