#!/usr/bin/env python3
"""Convert sprites/*.txt (ASCII, '#' = black) or sprites/*.png (any size,
dark pixels = black; needs Pillow) into main/sprites.h.

File names are <mood>_<frame>.(txt|png); frames are numbered from 0.
Moods the firmware knows: idle working waiting listening thinking celebrate
error sleeping offline. A missing mood falls back to idle at runtime."""
import glob
import os
import re

ROOT = os.path.join(os.path.dirname(__file__), "..")
MOODS = ["idle", "working", "waiting", "listening", "thinking", "celebrate", "error", "sleeping", "offline"]


def load(path):
    if path.endswith(".txt"):
        rows = [r.rstrip("\n") for r in open(path) if r.strip()]
        return len(rows[0]), len(rows), [[ch == "#" for ch in r] for r in rows]
    from PIL import Image  # noqa: PLC0415
    img = Image.open(path).convert("L")
    w, h = img.size
    return w, h, [[img.getpixel((x, y)) < 128 for x in range(w)] for y in range(h)]


def pack(w, h, px):
    out = []
    stride = (w + 7) // 8
    for y in range(h):
        for b in range(stride):
            byte = 0
            for bit in range(8):
                x = b * 8 + bit
                if x < w and px[y][x]:
                    byte |= 0x80 >> bit
            out.append(byte)
    return out


def main():
    frames = {}
    for path in sorted(glob.glob(os.path.join(ROOT, "sprites", "*"))):
        m = re.match(r"([a-z]+)_(\d+)\.(txt|png)$", os.path.basename(path))
        if m:
            frames.setdefault(m.group(1), {})[int(m.group(2))] = path
    lines = ["// Generated by tools/sprites.py — do not edit by hand.", "#pragma once", "#include \"gfx.h\"", ""]
    table = []
    for mood in MOODS:
        names = []
        for idx in sorted(frames.get(mood, {})):
            w, h, px = load(frames[mood][idx])
            data = ", ".join(f"0x{b:02x}" for b in pack(w, h, px))
            name = f"spr_{mood}_{idx}"
            lines.append(f"static const uint8_t {name}_bits[] = {{{data}}};")
            lines.append(f"static const sprite_t {name} = {{{w}, {h}, {name}_bits}};")
            names.append(name)
        if names:
            lines.append(f"static const sprite_t *const anim_{mood}[] = {{{', '.join('&' + n for n in names)}}};")
            table.append(f"    [MOOD_{mood.upper()}] = {{anim_{mood}, {len(names)}}},")
        else:
            table.append(f"    [MOOD_{mood.upper()}] = {{NULL, 0}},")
        lines.append("")
    lines.append("static const animation_t ANIMATIONS[MOOD_COUNT] = {")
    lines.extend(table)
    lines.append("};")
    with open(os.path.join(ROOT, "main", "sprites.h"), "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote main/sprites.h ({sum(len(v) for v in frames.values())} frames)")


if __name__ == "__main__":
    main()
