#!/usr/bin/env node
const input = JSON.parse(require('fs').readFileSync(0, 'utf-8'));
const lineCount = (input.userPromptSubmit.prompt.match(/\n/g) || []).length + 1;
console.log(JSON.stringify({
  cancel: false,
  contextModification: "Line count: " + lineCount,
  errorMessage: ""
}));
