export interface OAuthCallbackPayload {
	url: URL;
	code?: string;
	state?: string;
	provider?: string;
	error?: string;
}

type Deferred<T> = {
	promise: Promise<T>;
	resolve: (value: T) => void;
};

function createDeferred<T>(): Deferred<T> {
	let resolve!: (value: T) => void;
	const promise = new Promise<T>((res) => {
		resolve = res;
	});
	return { promise, resolve };
}

function getHostHeaderValues(
	request: import("node:http").IncomingMessage,
): string[] {
	const values: string[] = [];
	for (let index = 0; index < request.rawHeaders.length; index += 2) {
		if (request.rawHeaders[index]?.toLowerCase() === "host") {
			values.push(request.rawHeaders[index + 1] ?? "");
		}
	}
	return values;
}

function normalizeHttpAuthority(value: string): string | undefined {
	try {
		const url = new URL(`http://${value}`);
		if (
			url.username ||
			url.password ||
			url.pathname !== "/" ||
			url.search ||
			url.hash
		) {
			return undefined;
		}
		return url.host;
	} catch {
		return undefined;
	}
}

function parseCallbackRequestTarget(
	requestTarget: string,
	callbackOrigin: string,
): URL | undefined {
	try {
		const requestUrl = requestTarget.startsWith("/")
			? new URL(`${callbackOrigin}${requestTarget}`)
			: /^[a-z][a-z\d+.-]*:\/\//i.test(requestTarget)
				? new URL(requestTarget)
				: undefined;
		if (
			!requestUrl ||
			requestUrl.username ||
			requestUrl.password ||
			requestUrl.hash
		) {
			return undefined;
		}
		return requestUrl;
	} catch {
		return undefined;
	}
}

function sendTextResponse(
	response: import("node:http").ServerResponse,
	statusCode: number,
	body: string,
): void {
	response.statusCode = statusCode;
	response.setHeader("Content-Type", "text/plain; charset=utf-8");
	response.setHeader("X-Content-Type-Options", "nosniff");
	response.end(body);
}

export interface OAuthServerListeningInfo {
	host: string;
	port: number;
	callbackUrl: string;
}

export interface OAuthServerCloseInfo {
	host: string;
	port: number;
}

export interface LocalOAuthServerOptions {
	host?: string;
	/**
	 * Hostname advertised in the callback URL while the socket remains bound to
	 * `host`. The only supported alias prevents provider-specific localhost
	 * requirements from widening the listener beyond the loopback interface.
	 */
	callbackHostname?: "127.0.0.1" | "localhost";
	ports: number[];
	callbackPath: string;
	timeoutMs?: number;
	expectedState?: string;
	/**
	 * Reject callbacks until `setExpectedState` binds the state generated by an
	 * authorization flow. This closes the interval between binding the listener
	 * and the provider producing its authorization URL.
	 */
	requireExpectedState?: boolean;
	successHtml?: string;
	/**
	 * Called when the local redirect server successfully binds to a port and is
	 * ready to receive the OAuth callback. Hosts can use this to display a
	 * "waiting for callback" status indicator or — in remote-development
	 * environments like JetBrains Gateway — to forward the port from the remote
	 * machine to the local machine where the user's browser is running.
	 *
	 * May be async; `startLocalOAuthServer` will **await** this callback before
	 * returning so that any setup it performs (e.g. port-forwarding) is
	 * guaranteed to complete before the caller opens the auth URL. Errors
	 * thrown by this callback are swallowed — they do not prevent the OAuth
	 * flow from proceeding.
	 */
	onListening?: (info: OAuthServerListeningInfo) => void | Promise<void>;
	/**
	 * Called when the local redirect server closes, either because the OAuth
	 * callback was received, the flow was cancelled, or the timeout elapsed.
	 * Hosts should use this to tear down any port-forward set up in
	 * `onListening` and clear any "waiting for callback" status UI.
	 *
	 * May be async; fired after the underlying server socket is closed.
	 */
	onClose?: (info: OAuthServerCloseInfo) => void | Promise<void>;
}

export interface LocalOAuthServer {
	callbackUrl: string;
	setExpectedState: (state: string) => void;
	waitForCallback: () => Promise<OAuthCallbackPayload | null>;
	cancelWait: () => void;
	close: () => void;
}

export async function startLocalOAuthServer(
	options: LocalOAuthServerOptions,
): Promise<LocalOAuthServer> {
	const http = await import("node:http");

	const host = options.host ?? "127.0.0.1";
	const callbackHostname = options.callbackHostname ?? host;
	// The advertised hostname is provider policy; the socket bind is the network
	// boundary. Supporting Slack's literal `localhost` redirect must never turn a
	// loopback listener into an all-interface listener.
	if (
		callbackHostname !== host &&
		!(host === "127.0.0.1" && callbackHostname === "localhost")
	) {
		throw new Error(
			"OAuth callback hostname may only alias a 127.0.0.1 listener as localhost.",
		);
	}
	const timeoutMs = options.timeoutMs ?? 5 * 60 * 1000;
	const successHtml = options.successHtml ?? HTML_CONTENT;
	if (
		options.expectedState !== undefined &&
		options.expectedState.length === 0
	) {
		throw new Error("OAuth callback state cannot be empty.");
	}

	const deferred = createDeferred<OAuthCallbackPayload | null>();
	let settled = false;
	let timeout: ReturnType<typeof setTimeout> | null = null;
	let activeServer: import("node:http").Server | null = null;
	let boundPort: number | null = null;
	let expectedState = options.expectedState;
	let expectedStateConfigured = expectedState !== undefined;

	const setExpectedState = (state: string) => {
		if (state.length === 0) {
			throw new Error("OAuth callback state cannot be empty.");
		}
		if (expectedStateConfigured) {
			throw new Error("OAuth callback state is already configured.");
		}
		expectedState = state;
		expectedStateConfigured = true;
	};

	const settle = (value: OAuthCallbackPayload | null) => {
		if (settled) return;
		settled = true;
		deferred.resolve(value);
	};

	const close = () => {
		if (timeout) {
			clearTimeout(timeout);
			timeout = null;
		}
		const closingPort = boundPort;
		boundPort = null;
		if (activeServer) {
			activeServer.close();
			// `Server.close()` only stops accepting new connections; existing
			// keep-alive sockets keep working. A browser / global-fetch connection
			// pool keeps such a socket to the (fixed) callback port alive, and a
			// later request to that port can be delivered over the pooled socket to
			// this server even after it has settled — so a subsequent OAuth flow
			// reusing the port would have its callback delivered here and never
			// resolve. Drop lingering connections so no pooled socket outlives this
			// server.
			activeServer.closeAllConnections?.();
			activeServer = null;
		}
		if (closingPort !== null && options.onClose) {
			void Promise.resolve(options.onClose({ host, port: closingPort })).catch(
				() => {},
			);
		}
	};

	const waitForCallback = async () => {
		timeout = setTimeout(() => {
			close();
			settle(null);
		}, timeoutMs);
		return deferred.promise;
	};

	for (const port of options.ports) {
		const server = http.createServer((req, res) => {
			try {
				const callbackOrigin = new URL(`http://${callbackHostname}:${port}`)
					.origin;
				const expectedAuthority = new URL(callbackOrigin).host;
				const requestUrl = parseCallbackRequestTarget(
					req.url ?? "",
					callbackOrigin,
				);
				const hostHeaders = getHostHeaderValues(req);
				// Validate both HTTP authority representations. Proxies and absolute-form
				// request targets can disagree with Host; accepting either independently
				// would let an unrelated local origin feed state/code into this listener.
				if (
					!requestUrl ||
					hostHeaders.length !== 1 ||
					normalizeHttpAuthority(hostHeaders[0] ?? "") !== expectedAuthority ||
					requestUrl.origin !== callbackOrigin
				) {
					sendTextResponse(res, 400, "Invalid callback origin");
					return;
				}

				if (requestUrl.pathname !== options.callbackPath) {
					sendTextResponse(res, 404, "Not found");
					return;
				}

				const payload: OAuthCallbackPayload = {
					url: requestUrl,
					code: requestUrl.searchParams.get("code") ?? undefined,
					state: requestUrl.searchParams.get("state") ?? undefined,
					provider: requestUrl.searchParams.get("provider") ?? undefined,
					error: requestUrl.searchParams.get("error") ?? undefined,
				};

				if (options.requireExpectedState && !expectedStateConfigured) {
					sendTextResponse(res, 400, "OAuth callback state is not ready");
					return;
				}

				if (expectedStateConfigured && payload.state !== expectedState) {
					sendTextResponse(res, 400, "State mismatch");
					return;
				}

				if (payload.error) {
					sendTextResponse(res, 400, `Authentication failed: ${payload.error}`);
					close();
					settle(payload);
					return;
				}

				if (!payload.code) {
					sendTextResponse(res, 400, "Missing authorization code");
					return;
				}

				res.statusCode = 200;
				res.setHeader("Content-Type", "text/html; charset=utf-8");
				res.end(successHtml);
				close();
				settle(payload);
			} catch {
				sendTextResponse(res, 500, "Internal error");
			}
		});

		const bindResult = await new Promise<{
			bound: boolean;
			error?: NodeJS.ErrnoException;
		}>((resolve) => {
			const onError = (error: NodeJS.ErrnoException) => {
				server.off("error", onError);
				resolve({ bound: false, error });
			};

			server.once("error", onError);
			server.listen(port, host, () => {
				server.off("error", onError);
				activeServer = server;
				resolve({ bound: true });
			});
		});

		if (bindResult.error) {
			if (bindResult.error.code === "EADDRINUSE") {
				continue;
			}
			close();
			throw bindResult.error;
		}

		if (bindResult.bound) {
			boundPort = port;
			const callbackUrl = `http://${callbackHostname}:${port}${options.callbackPath}`;
			if (options.onListening) {
				await Promise.resolve(
					options.onListening({ host, port, callbackUrl }),
				).catch(() => {});
			}
			return {
				callbackUrl,
				setExpectedState,
				waitForCallback,
				cancelWait: () => {
					close();
					settle(null);
				},
				close: () => {
					close();
					settle(null);
				},
			};
		}
	}

	return {
		callbackUrl: "",
		setExpectedState: () => {},
		waitForCallback: async () => null,
		cancelWait: () => {},
		close: () => {},
	};
}

const HTML_CONTENT = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Authentication Successful</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
    min-height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
    background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
    color: #fff;
  }
  .container { text-align: center; padding: 48px; max-width: 420px; }
  .icon {
    width: 72px; height: 72px; margin: 0 auto 24px;
    background: linear-gradient(135deg, #10a37f 0%, #1a7f64 100%);
    border-radius: 50%;
    display: flex; align-items: center; justify-content: center;
  }
  .icon svg { width: 36px; height: 36px; stroke: #fff; stroke-width: 3; fill: none; }
  h1 { font-size: 24px; font-weight: 600; margin-bottom: 12px; }
  p { font-size: 15px; color: rgba(255,255,255,0.7); line-height: 1.5; }
  .closing { margin-top: 32px; font-size: 13px; color: rgba(255,255,255,0.5); }
</style>
</head>
<body>
<div class="container">
  <div class="icon">
    <svg viewBox="0 0 24 24"><polyline points="20 6 9 17 4 12"></polyline></svg>
  </div>
  <h1>Authentication Successful</h1>
  <p>You're now signed in. You can close this window.</p>
  <p class="closing">This window will close automatically...</p>
</div>
<script>setTimeout(() => window.close(), 3000);</script>
</body>
</html>`;
