// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by proto/build-proto.js

import { handleDiffServiceRequest, handleDiffServiceStreamingRequest } from "./diff/index"
import { handleEnvServiceRequest, handleEnvServiceStreamingRequest } from "./env/index"
import { StreamingResponseHandler } from "./host-grpc-handler"
import { handleUriServiceRequest, handleUriServiceStreamingRequest } from "./uri/index"
import { handleWatchServiceRequest, handleWatchServiceStreamingRequest } from "./watch/index"
import { handleWindowServiceRequest, handleWindowServiceStreamingRequest } from "./window/index"
import { handleWorkspaceServiceRequest, handleWorkspaceServiceStreamingRequest } from "./workspace/index"

/**
 * Configuration for a host service handler
 */
export interface HostServiceHandlerConfig {
	requestHandler: (method: string, message: any) => Promise<any>
	streamingHandler: (
		method: string,
		message: any,
		responseStream: StreamingResponseHandler,
		requestId?: string,
	) => Promise<void>
}

/**
 * Map of host service names to their handler configurations
 */
export const hostServiceHandlers: Record<string, HostServiceHandlerConfig> = {
	"host.UriService": {
		requestHandler: handleUriServiceRequest,
		streamingHandler: handleUriServiceStreamingRequest,
	},
	"host.WatchService": {
		requestHandler: handleWatchServiceRequest,
		streamingHandler: handleWatchServiceStreamingRequest,
	},
	"host.WorkspaceService": {
		requestHandler: handleWorkspaceServiceRequest,
		streamingHandler: handleWorkspaceServiceStreamingRequest,
	},
	"host.EnvService": {
		requestHandler: handleEnvServiceRequest,
		streamingHandler: handleEnvServiceStreamingRequest,
	},
	"host.WindowService": {
		requestHandler: handleWindowServiceRequest,
		streamingHandler: handleWindowServiceStreamingRequest,
	},
	"host.DiffService": {
		requestHandler: handleDiffServiceRequest,
		streamingHandler: handleDiffServiceStreamingRequest,
	},
}
