"""
AI-Hydro Project Session
=========================
Project-level research state that spans multiple sessions, topics, and data
sources — not tied to any single site or data source.

A Project is the top-level unit of research organisation in AI-Hydro v1.2+.
Each project owns:
  - A collection of associated research sessions (referenced by session_id)
  - A literature folder (user drops PDFs / text files there)
  - An auto-generated literature index (literature_index.md)
  - A project-level research journal (journal entries written by the agent)
  - Free-form notes and topic tags

Storage layout
--------------
~/.aihydro/
    projects/
        <project_name>/
            project.json          ← project metadata (this class serialises here)
            literature/           ← user drops papers/docs here
            literature_index.md   ← auto-generated by index_literature tool
    sessions/
        <session_id>.json         ← research sessions (referenced by project)
"""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

_PROJECTS_DIR = Path.home() / ".aihydro" / "projects"

# Only allow safe project names — prevents path traversal via project_name parameter
_VALID_PROJECT_NAME = re.compile(r"^[a-zA-Z0-9_-]{1,64}$")
_SESSIONS_DIR = Path.home() / ".aihydro" / "sessions"

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent.parent
_RULES_DIR_NAME = ".aihydrorules"


class ProjectSession:
    """Project-level research state spanning multiple sessions and topics."""

    def __init__(self, name: str) -> None:
        self.name: str = name
        self.description: str = ""
        self.session_ids: list[str] = []        # associated research sessions
        self.topics: list[str] = []             # free-form topic tags
        self.literature_dir: str | None = None  # path to literature folder
        self.journal: list[dict] = []           # timestamped experiment log entries
        self.notes: list[str] = []              # free-form notes
        self.created_at: str = datetime.now(timezone.utc).isoformat()
        self.updated_at: str = self.created_at

    # ------------------------------------------------------------------
    # Backward compat alias
    # ------------------------------------------------------------------

    @property
    def gauge_ids(self) -> list[str]:
        """Backward-compat alias — same list as session_ids."""
        return self.session_ids

    # ------------------------------------------------------------------
    # Paths
    # ------------------------------------------------------------------

    @classmethod
    def _validate_name(cls, name: str) -> str:
        """Raise ValueError if name contains path-traversal characters."""
        if not _VALID_PROJECT_NAME.match(name):
            raise ValueError(
                f"Invalid project name: {name!r}. "
                "Use only letters, digits, underscores, and hyphens (max 64 chars)."
            )
        return name

    @classmethod
    def _dir(cls, name: str) -> Path:
        cls._validate_name(name)
        return _PROJECTS_DIR / name

    @classmethod
    def _path(cls, name: str) -> Path:
        return cls._dir(name) / "project.json"

    @property
    def literature_path(self) -> Path:
        """Default literature folder inside the project directory."""
        return self._dir(self.name) / "literature"

    @property
    def literature_index_path(self) -> Path:
        return self._dir(self.name) / "literature_index.md"

    # ------------------------------------------------------------------
    # Persistence
    # ------------------------------------------------------------------

    @classmethod
    def load(cls, name: str) -> ProjectSession:
        """Load existing project or return a fresh one."""
        path = cls._path(name)
        if not path.exists():
            return cls(name)
        with open(path) as f:
            raw = json.load(f)
        p = cls(name)
        p.description = raw.get("description", "")
        # Support both "session_ids" (new) and "gauge_ids" (legacy)
        p.session_ids = raw.get("session_ids") or raw.get("gauge_ids", [])
        p.topics = raw.get("topics", [])
        p.literature_dir = raw.get("literature_dir")
        p.journal = raw.get("journal", [])
        p.notes = raw.get("notes", [])
        p.created_at = raw.get("created_at", p.created_at)
        p.updated_at = raw.get("updated_at", p.updated_at)
        return p

    @classmethod
    def list_all(cls) -> list[str]:
        """Return names of all existing projects."""
        if not _PROJECTS_DIR.exists():
            return []
        return [d.name for d in _PROJECTS_DIR.iterdir() if d.is_dir()]

    def _get_workspace_dir(self) -> str | None:
        """Return workspace_dir from the first associated session that has one."""
        from ai_hydro.session.store import HydroSession
        for sid in self.session_ids:
            try:
                s = HydroSession.load(sid)
                if s.workspace_dir:
                    return s.workspace_dir
            except Exception:
                continue
        return None

    def save(self) -> None:
        self.updated_at = datetime.now(timezone.utc).isoformat()
        self._dir(self.name).mkdir(parents=True, exist_ok=True)
        with open(self._path(self.name), "w") as f:
            json.dump(self._to_raw(), f, indent=2)
        # Auto-detect workspace from associated sessions so project context
        # is written to the correct .aihydrorules/research.md (not repo root).
        self.write_research_context(workspace_dir=self._get_workspace_dir())

    def _to_raw(self) -> dict:
        return {
            "name": self.name,
            "description": self.description,
            "session_ids": self.session_ids,
            "topics": self.topics,
            "literature_dir": self.literature_dir,
            "journal": self.journal,
            "notes": self.notes,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }

    # ------------------------------------------------------------------
    # Session management
    # ------------------------------------------------------------------

    def add_session(self, session_id: str) -> bool:
        """Associate a session with this project. Returns True if newly added."""
        if session_id not in self.session_ids:
            self.session_ids.append(session_id)
            return True
        return False

    def remove_session(self, session_id: str) -> bool:
        """Disassociate a session. Returns True if it was present."""
        if session_id in self.session_ids:
            self.session_ids.remove(session_id)
            return True
        return False

    # Backward-compat aliases
    def add_gauge(self, session_id: str) -> bool:
        return self.add_session(session_id)

    def remove_gauge(self, session_id: str) -> bool:
        return self.remove_session(session_id)

    # ------------------------------------------------------------------
    # Journal
    # ------------------------------------------------------------------

    def log_entry(self, text: str, tags: list[str] | None = None) -> dict:
        """Add a timestamped journal entry."""
        entry = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "text": text,
            "tags": tags or [],
        }
        self.journal.append(entry)
        return entry

    def search_journal(self, query: str) -> list[dict]:
        """Full-text search over journal entries."""
        q = query.lower()
        return [e for e in self.journal if q in e.get("text", "").lower()
                or any(q in t.lower() for t in e.get("tags", []))]

    # ------------------------------------------------------------------
    # Cross-session analytics
    # ------------------------------------------------------------------

    def session_summaries(self) -> list[dict]:
        """Load and summarise all associated research sessions."""
        from ai_hydro.session.store import HydroSession
        results = []
        for sid in self.session_ids:
            try:
                s = HydroSession.load(sid)
                results.append(s.summary())
            except Exception:
                results.append({"session_id": sid, "error": "could not load"})
        return results

    # Backward-compat alias
    def gauge_summaries(self) -> list[dict]:
        return self.session_summaries()

    def search_experiments(self, query: str) -> list[dict]:
        """
        Search across all sessions for results matching the query.

        Searches JSON representations of stored slot data. Useful for
        questions like "which sessions have BFI > 0.6" (agent can filter
        from the returned snippets) or "show me sessions where I ran LSTM".
        """
        from ai_hydro.session.store import HydroSession
        q = query.lower()
        matches: list[dict] = []
        for sid in self.session_ids:
            try:
                s = HydroSession.load(sid)
                for slot in s.computed():
                    result = s.get(slot)
                    if not result:
                        continue
                    blob = json.dumps(result).lower()
                    notes_blob = " ".join(s.notes).lower()
                    if q in blob or q in notes_blob:
                        data = result.get("data", {})
                        snippet = dict(list(data.items())[:8])
                        matches.append({
                            "session_id": sid,
                            "slot": slot,
                            "snippet": snippet,
                        })
            except Exception:
                continue
        return matches

    def compare_sessions(
        self,
        session_ids: list[str] | None = None,
        slots: list[str] | None = None,
    ) -> dict[str, Any]:
        """
        Side-by-side comparison of metrics across sessions.

        Parameters
        ----------
        session_ids : list[str], optional
            Subset to compare. Defaults to all project sessions.
        slots : list[str], optional
            Which result slots to include. Defaults to signatures + model.
        """
        from ai_hydro.session.store import HydroSession
        target_sessions = session_ids or self.session_ids
        target_slots = slots or ["signatures", "geomorphic", "camels", "model"]
        comparison: dict[str, Any] = {}
        for sid in target_sessions:
            try:
                s = HydroSession.load(sid)
                row: dict[str, Any] = {}
                for slot in target_slots:
                    result = s.get(slot)
                    if result:
                        row[slot] = result.get("data", {})
                comparison[sid] = row
            except Exception:
                comparison[sid] = {"error": "could not load"}
        return comparison

    # Backward-compat alias
    def compare_gauges(
        self,
        gauge_ids: list[str] | None = None,
        slots: list[str] | None = None,
    ) -> dict[str, Any]:
        return self.compare_sessions(session_ids=gauge_ids, slots=slots)

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------

    def summary(self) -> dict:
        return {
            "name": self.name,
            "description": self.description,
            "session_ids": self.session_ids,
            "n_sessions": len(self.session_ids),
            "topics": self.topics,
            "literature_dir": self.literature_dir or str(self.literature_path),
            "n_journal_entries": len(self.journal),
            "n_notes": len(self.notes),
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }

    # ------------------------------------------------------------------
    # research.md sync (project-aware)
    # ------------------------------------------------------------------

    def write_research_context(self, workspace_dir: str | None = None) -> None:
        """
        Write a project-level digest to .aihydrorules/research.md.

        Location: workspace_dir/.aihydrorules/research.md when workspace_dir
        is provided, otherwise repo-root/.aihydrorules/research.md (dev mode).
        The extension auto-loads this file into every conversation.
        """
        lines: list[str] = [
            f"# Research Project: {self.name}",
            f"**Updated**: {self.updated_at[:10]}",
        ]

        if self.description:
            lines.append(f"**Description**: {self.description}")
        if self.topics:
            lines.append(f"**Topics**: {', '.join(self.topics)}")
        lines.append("")

        # Session overview
        if self.session_ids:
            lines.append(f"## Sessions ({len(self.session_ids)} associated)")
            from ai_hydro.session.store import HydroSession
            for sid in self.session_ids:
                try:
                    s = HydroSession.load(sid)
                    computed = s.computed()
                    display = s.site_name or s.site_id or sid
                    label = (
                        f"  - **{display}** (`{sid}`): "
                        f"{', '.join(computed) if computed else 'no results yet'}"
                    )
                    if s.signatures:
                        bfi = s.signatures.get("data", {}).get("baseflow_index")
                        if bfi is not None:
                            label += f" (BFI={bfi:.2f})"
                    if s.model:
                        nse = s.model.get("data", {}).get("nse")
                        if nse is not None:
                            label += f" (NSE={nse:.3f})"
                    lines.append(label)
                except Exception:
                    lines.append(f"  - **{sid}**: could not load")
            lines.append("")

        # Recent journal entries
        if self.journal:
            lines.append(f"## Recent Journal ({len(self.journal)} total)")
            for entry in self.journal[-3:]:
                ts = entry.get("timestamp", "")[:10]
                text = entry.get("text", "")
                lines.append(f"  - [{ts}] {text}")
            lines.append("")

        # Notes
        if self.notes:
            lines.append("## Notes")
            for note in self.notes[-5:]:
                lines.append(f"  - {note}")
            lines.append("")

        # Literature
        lit_dir = Path(self.literature_dir) if self.literature_dir else self.literature_path
        if lit_dir.exists():
            docs = list(lit_dir.glob("*"))
            readable = [d for d in docs if d.suffix.lower() in (".pdf", ".txt", ".md")]
            if readable:
                lines.append(f"## Literature ({len(readable)} documents in {lit_dir})")
                if self.literature_index_path.exists():
                    lines.append("  - Index available: run `search_literature` to query papers.")
                else:
                    lines.append("  - Not yet indexed: run `index_literature` to build the index.")
                lines.append("")

        lines.append("> *Auto-generated by ProjectSession — do not edit manually.*")

        base = Path(workspace_dir) if workspace_dir else _REPO_ROOT
        research_md = base / _RULES_DIR_NAME / "research.md"
        research_md.parent.mkdir(parents=True, exist_ok=True)
        research_md.write_text("\n".join(lines))
