// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by proto/build-proto.js

import { createServiceRegistry, ServiceMethodHandler, StreamingMethodHandler } from "../host-grpc-service"
import { registerAllMethods } from "./methods"

// Create diff service registry
const diffService = createServiceRegistry("diff")

// Export the method handler types and registration function
export type DiffMethodHandler = ServiceMethodHandler
export type DiffStreamingMethodHandler = StreamingMethodHandler
export const registerMethod = diffService.registerMethod

// Export the request handlers
export const handleDiffServiceRequest = diffService.handleRequest
export const handleDiffServiceStreamingRequest = diffService.handleStreamingRequest
export const isStreamingMethod = diffService.isStreamingMethod

// Register all diff methods
registerAllMethods()
