#!/usr/bin/env bun
/**
 * Generates `src/generated/message-keys.ts` from `locales/en.json`.
 *
 * The generated union type lets consumers get compile-time errors for typos in
 * translation keys. Run after adding/removing keys to `en.json`:
 *
 *   bun run i18n:types
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const root = join(import.meta.dir, "..");
const enPath = join(root, "locales", "en.json");
const outPath = join(root, "src", "generated", "message-keys.ts");

const raw = readFileSync(enPath, "utf8");
const catalog = JSON.parse(raw) as Record<string, unknown>;

const keys = Object.keys(catalog).sort();
if (keys.length === 0) {
	throw new Error("locales/en.json is empty; nothing to generate");
}

const lines = [
	"// AUTO-GENERATED by scripts/generate-message-types.ts — do not edit by hand.",
	"// Regenerate with `bun run i18n:types` after changing locales/en.json.",
	"",
	"/** Every message key that exists in the English (source) catalog. */",
	"export type MessageKey =",
];
for (const key of keys) {
	lines.push(`\t| ${JSON.stringify(key)}`);
}
lines.push(";", "");
lines.push(
	"/** Message templates of the English (source) catalog, typed as const. */",
);
lines.push("export const MESSAGE_KEYS = [");
for (const key of keys) {
	lines.push(`\t${JSON.stringify(key)},`);
}
lines.push("] as const;", "");

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, lines.join("\n"), "utf8");
console.log(
	`Wrote ${keys.length} message keys to ${outPath.replace(root, ".")}`,
);
