/**
 * Tool parameter tag names shared by XML/JSON assistant-message parsers.
 * Kept in a standalone module so parse-json-tool-use.ts does not circular-import index.ts.
 */
export const toolParamNames = [
	"command",
	"requires_approval",
	"path",
	"absolutePath",
	"content",
	"diff",
	"regex",
	"file_pattern",
	"recursive",
	"action",
	"url",
	"coordinate",
	"text",
	"query",
	"allowed_domains",
	"blocked_domains",
	"prompt",
	"server_name",
	"tool_name",
	"arguments",
	"uri",
	"question",
	"options",
	"response",
	"result",
	"context",
	"title",
	"what_happened",
	"steps_to_reproduce",
	"api_request_output",
	"additional_context",
	"needs_more_exploration",
	"task_progress",
	"timeout",
	"input",
	"from_ref",
	"to_ref",
	"skill_name",
	"prompt_1",
	"prompt_2",
	"prompt_3",
	"prompt_4",
	"prompt_5",
	"start_line",
	"end_line",
] as const

export type ToolParamName = (typeof toolParamNames)[number]
