/**
 * Auto-generated provider loader registry.
 *
 * WARNING: DO NOT EDIT THIS FILE MANUALLY.
 *
 * Generated by: @clinebot/llms/scripts/generate-provider-loaders.ts
 */

import type { ModelCollection } from "./schemas/index";

export type GeneratedProviderLoaderEntry = readonly [
	providerId: string,
	load: () => Promise<ModelCollection>,
];

export const GENERATED_PROVIDER_LOADER_ENTRIES: GeneratedProviderLoaderEntry[] =
	[
		[
			"aihubmix",
			async () => (await import("./providers/aihubmix")).AIHUBMIX_PROVIDER,
		],
		[
			"anthropic",
			async () => (await import("./providers/anthropic")).ANTHROPIC_PROVIDER,
		],
		[
			"asksage",
			async () => (await import("./providers/asksage")).ASKSAGE_PROVIDER,
		],
		[
			"baseten",
			async () => (await import("./providers/baseten")).BASETEN_PROVIDER,
		],
		[
			"bedrock",
			async () => (await import("./providers/bedrock")).BEDROCK_PROVIDER,
		],
		[
			"cerebras",
			async () => (await import("./providers/cerebras")).CEREBRAS_PROVIDER,
		],
		[
			"claude-code",
			async () =>
				(await import("./providers/claude-code")).CLAUDE_CODE_PROVIDER,
		],
		["cline", async () => (await import("./providers/cline")).CLINE_PROVIDER],
		[
			"deepseek",
			async () => (await import("./providers/deepseek")).DEEPSEEK_PROVIDER,
		],
		["dify", async () => (await import("./providers/dify")).DIFY_PROVIDER],
		[
			"doubao",
			async () => (await import("./providers/doubao")).DOUBAO_PROVIDER,
		],
		[
			"fireworks",
			async () => (await import("./providers/fireworks")).FIREWORKS_PROVIDER,
		],
		[
			"gemini",
			async () => (await import("./providers/gemini")).GEMINI_PROVIDER,
		],
		["groq", async () => (await import("./providers/groq")).GROQ_PROVIDER],
		["hicap", async () => (await import("./providers/hicap")).HICAP_PROVIDER],
		[
			"huawei-cloud-maas",
			async () =>
				(await import("./providers/huawei-cloud-maas"))
					.HUAWEI_CLOUD_MAAS_PROVIDER,
		],
		[
			"huggingface",
			async () =>
				(await import("./providers/huggingface")).HUGGINGFACE_PROVIDER,
		],
		[
			"litellm",
			async () => (await import("./providers/litellm")).LITELLM_PROVIDER,
		],
		[
			"lmstudio",
			async () => (await import("./providers/lmstudio")).LMSTUDIO_PROVIDER,
		],
		[
			"minimax",
			async () => (await import("./providers/minimax")).MINIMAX_PROVIDER,
		],
		[
			"mistral",
			async () => (await import("./providers/mistral")).MISTRAL_PROVIDER,
		],
		[
			"moonshot",
			async () => (await import("./providers/moonshot")).MOONSHOT_PROVIDER,
		],
		[
			"nebius",
			async () => (await import("./providers/nebius")).NEBIUS_PROVIDER,
		],
		[
			"nousResearch",
			async () =>
				(await import("./providers/nous-research")).NOUS_RESEARCH_PROVIDER,
		],
		["oca", async () => (await import("./providers/oca")).OCA_PROVIDER],
		[
			"ollama",
			async () => (await import("./providers/ollama")).OLLAMA_PROVIDER,
		],
		[
			"openai-codex",
			async () =>
				(await import("./providers/openai-codex")).OPENAI_CODEX_PROVIDER,
		],
		[
			"openai-native",
			async () => (await import("./providers/openai")).OPENAI_PROVIDER,
		],
		[
			"opencode",
			async () => (await import("./providers/opencode")).OPENCODE_PROVIDER,
		],
		[
			"openrouter",
			async () => (await import("./providers/openrouter")).OPENROUTER_PROVIDER,
		],
		["qwen", async () => (await import("./providers/qwen")).QWEN_PROVIDER],
		[
			"qwen-code",
			async () => (await import("./providers/qwen-code")).QWEN_CODE_PROVIDER,
		],
		[
			"requesty",
			async () => (await import("./providers/requesty")).REQUESTY_PROVIDER,
		],
		[
			"sambanova",
			async () => (await import("./providers/sambanova")).SAMBANOVA_PROVIDER,
		],
		[
			"sapaicore",
			async () => (await import("./providers/sapaicore")).SAP_AI_CORE_PROVIDER,
		],
		[
			"together",
			async () => (await import("./providers/together")).TOGETHER_PROVIDER,
		],
		[
			"vercel-ai-gateway",
			async () =>
				(await import("./providers/vercel-ai-gateway"))
					.VERCEL_AI_GATEWAY_PROVIDER,
		],
		[
			"vertex",
			async () => (await import("./providers/vertex")).VERTEX_PROVIDER,
		],
		["xai", async () => (await import("./providers/xai")).XAI_PROVIDER],
		["zai", async () => (await import("./providers/zai")).ZAI_PROVIDER],
	];
