// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by proto/build-proto.js

// Import all method implementations
import { checkpointDiff } from "./checkpointDiff"
import { checkpointRestore } from "./checkpointRestore"
import { registerMethod } from "./index"

// Register all checkpoints service methods
export function registerAllMethods(): void {
	// Register each method with the registry
	registerMethod("checkpointDiff", checkpointDiff)
	registerMethod("checkpointRestore", checkpointRestore)
}
