// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by proto/build-proto.js

// Import all method implementations
import { clipboardReadText } from "./clipboardReadText"
import { clipboardWriteText } from "./clipboardWriteText"
import { registerMethod } from "./index"
import { openExternal } from "./openExternal"

// Register all env service methods
export function registerAllMethods(): void {
	// Register each method with the registry
	registerMethod("clipboardReadText", clipboardReadText)
	registerMethod("clipboardWriteText", clipboardWriteText)
	registerMethod("openExternal", openExternal)
}
