// Note: This list is temporary. Some items may remain in the long run,
// but our goal is to reduce it over time by continuously improving
// how we prepare the testing-platform environment.
export const NON_DETERMINISTIC_FIELDS = [
	"stateJson.distinctId",
	"stateJson.apiConfiguration.actModeApiProvider",
	"stateJson.apiConfiguration.planModeApiProvider",
	"stateJson.shouldShowAnnouncement",
	"stateJson.welcomeViewCompleted",
	"stateJson.focusChainFeatureFlagEnabled",
	"stateJson.clineMessages",
	"stateJson.taskHistory.cwdOnTaskInitialization",
	"stateJson.taskHistory.id",
	"stateJson.taskHistory.size",
	"stateJson.taskHistory.ts",
	"stateJson.taskHistory.ulid",
	"stateJson.taskHistory.cacheWrites",
	"stateJson.taskHistory.cacheReads",
	"stateJson.taskHistory.tokensIn",
	"stateJson.taskHistory.tokensOut",
	"stateJson.taskHistory.totalCost",
	"stateJson.currentTaskItem.cwdOnTaskInitialization",
	"stateJson.currentTaskItem.id",
	"stateJson.currentTaskItem.ts",
	"stateJson.currentTaskItem.ulid",
]
