// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by proto/build-proto.js

import { Controller } from "../controller/index"
import { StreamingResponseHandler } from "../controller/grpc-handler"
import { handleUriServiceRequest, handleUriServiceStreamingRequest } from "../../../hosts/vscode/uri/index"

/**
 * Configuration for a host service handler
 */
export interface HostServiceHandlerConfig {
	requestHandler: (controller: Controller, method: string, message: any) => Promise<any>
	streamingHandler: (
		controller: Controller,
		method: string,
		message: any,
		responseStream: StreamingResponseHandler,
		requestId?: string,
	) => Promise<void>
}

/**
 * Map of host service names to their handler configurations
 */
export const hostServiceHandlers: Record<string, HostServiceHandlerConfig> = {
	"host.UriService": {
		requestHandler: handleUriServiceRequest,
		streamingHandler: handleUriServiceStreamingRequest,
	},
}
